# 英文名转为中文名
names = {
    "alk": "阿尔克",
    "white_tiger": "白",
    "fire_dragon": "瓦格纳",
    "pirates_girl": "玛丽娜",
    "clarisse": "克拉莉丝",
    "brown_fighter": "索妮雅",
    "onmyoji_boy": "水善",
    "fox_oracle": "稻穗",
    "cagliostro": "卡莉奥丝特罗",
    "wind_spgirl": "希尔媞",
    "wind_oracle": "菲莉亚",
    "katana_ghost": "丛云",
    "mercenary": "雷恩",
    "ruin_girl": "奈芙提姆",
    "prince_zero": "拉杰尔特",
    "bodysuit_trooper": "艾可莉儿",
    "dimension_witch": "贝尔赛蒂亚",
    "veteran_hunter": "威隆",
    "dragon_slayer": "阿赛尔",
    "lady_summoner": "碧安卡",
    "kunoichi": "花火",
    "half_oni_boy": "阿须桐丸",
    "master_knight": "格莱德",
    "swallow_knight": "尤维尔",
    "bishop_girl": "莉洁儿",
    "mermaid": "亚美莉亚",
    "alice": "爱丽丝",
    "battle_guild_staff": "夏农",
    "spry_sailor": "拉纳",
    "thunder_dragon": "拉姆斯",
    "fox_scientist": "露娜露",
    "rec_android": "雷吉斯",
    "elf_soldier": "艾琳诺儿",
    "cat_shaman": "杰",
    "minotaur_girl": "米诺",
    "tiger_treasure_hunter": "米娅",
    "birdman": "奥罗尔",
    "samurai": "宗士郎",
    "elf_archer": "梅露希儿",
    "dog_slasher": "赫尔加",
    "sing_android": "蒂亚",
    "unicorn_lancer": "杰拉尔",
    "lightbullet_wiz": "艾莉亚",
    "palpebra_knight": "芬",
    "palpebra_knight_lady": "绮拉",
    "devil_princess": "阿露姆",
    "battle_maid": "玛丽安",
    "undead_boy": "安迪",
    "warlock": "里昂",
    "alchemist": "莉莉露",
    "pretty_witch": "梅米",
    "gunslinger": "伊莉斯",
    "monster_hunter": "哈修",
    "black_doctor": "仁",
    "cool_woman_soldier": "特蕾涅",
    "berserker": "吉斯拉多",
    "fire_shaman": "恩妮",
    "disciplined_swordman": "杰克",
    "sniper": "凯洛斯",
    "urban_soldier": "崔丝塔",
    "hard_face_soldier": "瓦尔塔",
    "nurse": "艾尔莎",
    "wolf_assassin": "克劳斯",
    "fox_companion": "白乃",
    "depraved_monk": "诲谕",
    "sailor_girl": "拉蒂",
    "cute_fafnir": "法夫",
    "mens_attire_girl": "莉可",
    "twin_blader": "优娜",
    "bee_girl": "赫妮",
    "lightning_fighter": "泰加",
    "outlaw_panther": "黑",
    "wolf_swordsman": "阿尔伯特",
    "oni_girl": "加津知",
    "sociable_mestizo": "泰奇安娜",
    "magic_boy": "科特",
    "student_gunsmith": "夏·丝丝",
    "highlander": "伊凡",
    "dryad": "茶露亚",
    "lich": "瑞西塔尔",
    "casino_dealer": "奈丝卡",
    "cat_fighter": "缪",
    "devil_clown": "菲勒斯",
    "herbalist": "荷莉",
    "spearman": "科那",
    "trap_errand": "贾斯塔",
    "priest": "可莉娜",
    "lady_gunner": "玛格丽特",
    "woman_knight": "赛希莉亚",
    "docking_beast": "欧雷欧",
    "exorcist_oldman": "劳尔",
    "half_knight": "米雷斯",
    "reporter": "璐璐卡",
    "reaper_girl": "法露伽",
    "chakram_shooter": "札里尔",
    "devil_woman_soldier": "厄莉",
    "informant": "紫苑",
    "arabic_swordman": "阿迪尔",
    "dark_nursemaid": "桃乐西亚",
    "bearish_darkwitch": "蕾贝卡",
    "guardian_golem": "魔像",
    "owl": "波吉特",
    "fox": "镰鼬",
    "kinoko": "蘑仔",
    "slango_red": "红波露",
    "spirit_fire": "火精",
    "slango_blue": "蓝波露",
    "slango_yellow": "黄波露",
    "paralysis_hedgehog": "帕拉鼠",
    "slango_green": "绿波露",
    "arisa": "亚里莎",
    "battle_maid_xm19": "玛丽安(圣诞)",
    "samurai_xm19": "宗士郎(圣诞)",
    "fox_oracle_xm19": "稻穗(圣诞)",
    "red_gunner": "卡农",
    "docking_beast_xm19": "欧雷欧(圣诞)",
    "fortuneteller": "芙拉",
    "dryad_xm19": "茶露亚(圣诞)",
    "heavenly_one": "诺埃妮",
    "lightbullet_wiz_ny20": "艾莉亚(新年)",
    "reporter_ny20": "璐璐卡(新年)",
    "bearish_darkwitch_ny20": "蕾贝卡(新年)",
    "swallow_knight_ny20": "尤维尔(新年)",
    "wild_wolfgirl": "加萝",
    "cat_fighter_ny20": "缪(新年)",
    "sword_beauty": "葵泽",
    "ice_witch": "赛法",
    "blade_witch": "莫弥亚",
    "black_hair_swordman": "阿德尼",
    "gang_girl": "凯特",
    "compliment_oiran": "菊野",
    "thunder_archer": "梅媞斯",
    "shapely_soldier": "蕾维",
    "beast_adventurer": "露",
    "birdwoman": "可兰",
    "monster_cook": "帕尔菲",
    "commander": "希丽奴",
    "bigwing_shaman": "西微",
    "deepsea_mage": "萨尔",
    "monster_attract": "诺塞尔",
    "black_wolf_knight": "罗尔夫",
    "mighty_striker": "巴拉克",
    "timid_kunoichi": "凉风",
    "illusionist": "伊路米",
    "starbreak_hunter": "塔吉斯",
    "combat_soldier": "贝瑞塔",
    "desert_wizard": "莫迪亚迦",
    "unleash_hunter": "霍普",
    "touyakiren_ceo": "拉芙",
    "lakeside_guardian": "里姆尼斯",
    "cursed_girl": "卡菈",
    "lady_android": "露迪",
    "unyielding_adventurer": "莱亚",
    "delusion_girl": "梅利露",
    "gentle_barten": "米格里",
    "tengu_girl": "小羽",
    "whitedog_beast": "芙洛丽塔",
    "junior_yearngirl": "克菈菈",
    "drawing_witch": "拉绮夏",
    "blade_dancer": "里布拉姆",
    "onmyo_attendant": "蛟",
    "blindness_gunner": "赛吉尔",
    "old_mercenary": "卑尔根",
    "machine_police_girl": "塞拉",
    "crybaby_shooter": "琪丽",
    "psycho_reaper": "索维",
    "tradition_healer": "哈丽莎",
    "kokkoro": "可可萝",
    "pecorine": "佩可莉姆",
    "kyaru": "凯露",
    "sanctuary_guard": "米尔米娜",
    "brave_mouse": "斯文",
    "big_gunner": "牡丹",
    "ruin_girl_halfanv": "奈芙提姆(礼服)",
    "olivia": "奥莉维尔",
    "pirates_gunner": "贝伊斯",
    "luna": "露娜",
    "little_shaman": "纱玛莎",
    "fake_princess": "普莉卡",
    "dimension_witch_smr20": "贝尔赛蒂亚(泳装)",
    "wind_dragon": "休尔特",
    "hidden_blader": "罗塞莉亚",
    "keylock_girl": "琪亚娜",
    "scout_girl": "莉塔",
    "prince_zero_smr20": "拉杰尔特(泳装)",
    "magic_sword_girl": "娜希尔",
    "dinosaur_hunter": "格里格",
    "moth_girl": "摩菈",
    "pirates_girl_smr20": "玛丽娜(泳装)",
    "tiger_treasure_hunter_smr20": "米娅(泳装)",
    "illusionist_smr20": "伊路米(泳装)",
    "casino_dealer_smr20": "奈丝卡(泳装)",
    "bishop_girl_smr20": "莉洁儿(泳装)",
    "lazy_genious": "涅迪",
    "neoviolin_musician": "莉菈",
    "alice_smr20": "爱丽丝(泳装)",
    "unicorn_lancer_smr20": "杰拉尔(泳装)",
    "lady_gunner_smr20": "玛格丽特(泳装)",
    "floating_girl": "芙拉娜",
    "high_priestess": "奥薇尔",
    "lamp_guide": "菲拉梅里亚",
    "vigilante_boy": "仓丸",
    "crazy_doctor": "布莱斯",
    "minamoto_sakura": "源樱",
    "nikaido_saki": "二阶堂咲",
    "yugiri": "夕雾",
    "yamada_tae": "山田多惠",
    "hoshikawa_ririi": "星川莉莉",
    "konno_junko": "绀野纯子",
    "mizuno_ai": "水野爱",
    "ekaki_onmyoji": "鹄",
    "sing_android_hw20": "蒂亚(万圣)",
    "fox_scientist_hw20": "露娜露(万圣)",
    "reaper_girl_hw20": "法露伽(万圣)",
    "priest_hw20": "可莉娜(万圣)",
    "dark_psygirl": "蒂妮",
    "sorceress_teacher": "妮可拉",
    "wild_boy": "哈奥",
    "illegal_herbalist": "塞尔玛",
    "elf_princess": "艾丝缇莉艾尔",
    "freeze_eye": "雷拉斯",
    "junior_soldier": "可莎",
    "devil_leader": "艾迪凯斯",
    "resistance_princess": "莉莉丝",
    "rec_android_1anv": "雷吉斯(周年)",
    "shy_assassin": "薇薇",
    "doctor_machine": "梅克",
    "sewing_girl": "莉莉安",
    "silent_ninja": "八云",
    "kunoichi_1anv": "花火(周年)",
    "wind_spgirl_1anv": "希尔媞(周年)",
    "wind_oracle_1anv": "菲莉亚(周年)",
    "woman_knight_1anv": "赛希莉亚(周年)",
    "devil_woman_soldier_1anv": "厄莉(周年)",
    "alk_1anv": "阿尔克(周年)",
    "lady_summoner_xm20": "碧安卡(圣诞)",
    "devil_princess_xm20": "阿露姆(圣诞)",
    "cool_woman_soldier_xm20": "特蕾涅(圣诞)",
    "black_hair_swordman_xm20": "阿德尼(圣诞)",
    "delusion_girl_xm20": "梅利露(圣诞)",
    "white_tiger_xm20": "白(圣诞)",
    "heavenly_two": "布茜",
    "timid_kunoichi_ny21": "凉风(新年)",
    "urban_soldier_ny21": "崔丝塔(新年)",
    "little_wizard": "托·蕾蕾妮",
    "lightbullet_wiz_vt21": "艾莉亚(情人节)",
    "whitedog_beast_vt21": "芙洛丽塔(情人节)",
    "halberd_princess": "托莉亚",
    "combat_animal": "芙拉菲",
    "wind_striker": "里卡尔德",
    "sea_violent": "蒂蕾特",
    "emilia": "爱蜜莉雅",
    "rem": "雷姆",
    "ram": "拉姆",
    "subaru": "菜月·昴",
    "doctor_pirate": "燎",
    "girl_and_mecha": "洛蒂",
    "punk_warrior": "艾蒂塔",
    "mystery_agent": "爱德华",
    "waterdragon_kunfu": "谢胧",
    "summoner_little": "珂艾特",
    "steel_lacrosse": "米迪",
    "skateboard_boy": "阿克塞姆",
    "onmyoji_boy_wt21": "水善(白情)",
    "wolf_assassin_wt21": "克劳斯(白情)",
    "crystal_swordman": "塞里奥尔",
    "noble_sorceress": "梅尔维奥拉",
    "electro_girl": "特尔娜",
    "desert_commander": "哈里达尔",
    "brown_fighter_dst21": "索妮雅(沙漠)",
    "dark_psygirl_dst21": "蒂妮(沙漠)",
    "kids_gunner": "鲁·鲁特",
    "ruin_lady": "索媞艾丝",
    "magical_bayonetter": "克亚雷",
    "general_toyakiren": "兹茵可",
    "walking_armor": "伦达尔",
    "beast_shaman": "涅维亚",
    "mummy_boy": "塔尔哈",
    "zeta": "塞达",
    "beatrix": "贝阿朵丽丝",
    "secret_observer": "吉泽尔",
    "desert_caravans": "塔维尔",
    "samurai_robot": "斩铁",
    "yokai_exterminator": "莲月",
    "cool_witch_girl": "皮亚莫",
    "sleep_puppy": "菲妮",
    "mermaid_1halfanv": "亚美莉亚(礼服)",
    "elf_princess_1halfanv": "艾丝缇莉艾尔(礼服)",
    "blindness_gunner_1halfanv": "赛吉尔(礼服)",
    "naginata_girl": "舞姬",
    "revenge_rabbit": "科迪",
    "hero_girl": "涅特",
    "tsundere_bountyhunter": "蕾缇希娅",
    "elder_guild_fighter": "玛奇斯",
    "stylish_witch": "珐颂",
    "desert_priest": "萨莉哈",
    "holy_mother": "玛姆娜莉亚",
    "machine_police_girl_smr21": "塞拉(泳装)",
    "resistance_princess_smr21": "莉莉丝(泳装)",
    "dragon_slayer_smr21": "阿赛尔(泳装)",
    "rookie_adventurer": "米蕾特",
    "bodysuit_trooper_smr21": "艾可莉儿(泳装)",
    "blackflower_wiz": "普莉姆拉",
    "dress_gunner": "艾芙琳",
    "bird_master": "路马尔克",
    "tengu_master": "豪岚",
    "bigwing_shaman_smr21": "西微(泳装)",
    "fox_oracle_smr21": "稻穗(泳装)",
    "fox_companion_smr21": "白乃(泳装)",
    "psycho_reaper_smr21": "索维(泳装)",
    "assistant_boy": "露西尔",

    "suzumiya_haruhi": "凉宫春日",
    "nagato_yuki": "长门有希",
    "asahina_mikuru": "朝比奈实玖瑠",
    "kyon": "阿虚",
    "koizumi_ituki": "古泉一树",

    "mercenary_smr21": "雷恩(浴衣)",
    "ruin_girl_smr21": "奈芙提姆(浴衣)",
    "formercorrupt_detective": "薇尔吉娅",
    "conjurer_girl": "菲·诺诺亚",
    "cyber_battergirl": "丝特莱纳",
    "horn_leader": "梅姆拉姆",
    "guildknight_leader": "泽赫尔",
    "warashi": "阿福",
    "waterdragon_kunfu_proud": "谢胧(百兽)",
    "dog_slasher_proud": "赫尔加(百兽)",
    "lion_boy": "提欧",
    "pilgrim_monk": "玛卡妮",
    "neoviolin_musician_hw21": "莉菈(圣诞)",
    "touyakiren_ceo_hw21": "拉芙(圣诞)",
    "spry_sailor_hw21": "拉纳(圣诞)",
    "sanctuary_guard_hw21": "米尔米娜(圣诞)",
    "psychic_yuki": "见岛勇希",
    "psychic_shouta": "伊野里翔太",
    "psychic_tomboygirl": "绯河凛音",
    "psychic_nao": "凪原直",
    "psychic_seiji": "鹰森诚司",
    "shadow_redhood": "琉农",
    "navy_officer": "芙拉克西斯",
    "psychic_tohru": "千岳十织",
    "psychic_projection": "影丘龙一",
    "pirates_girl_2anv": "玛丽娜(周年)",
    "summoner_little_2anv": "珂艾特(周年)",
    "stella_2anv": "史黛拉(周年)",
    "informant_2anv": "紫苑(周年)",
    "ice_witch_2anv": "赛法(周年)",
    "white_tiger_2anv": "白(周年)",
    "nurse_pirate": "皮西卡",
    "freeze_eye_xm21": "雷拉斯(圣诞)",
    "combat_animal_xm21": "芙拉菲(圣诞)",
    "devil_clown_xm21": "菲勒斯(圣诞)",

    "guild_front_girl": "普·莉莉艾",
    "merchant": "玛·露露夏",
    # boss
    "multi_battle_pickup_empress": "青之女王",
    # "white_tiger_ghost": "白虎",
    "white_tiger_ghost": "白虎的亡灵",
    # "lich": "不死王瑞西塔尔",
    "lich": "瑞西塔尔",
    "treant": "雷霆树妖",
    "orochi": "八岐大蛇",
    "ghost_fox": "狐妖",
    "administrator": "管理者",
    "security_armor": "Sec-5200Li",
    "boar_rider": "风将獠牙骑士",
    "arch_evil": "诅咒弧魔艾基尔",
    "hermit_crab": "寄居蟹船长",
    "kraken": "潮汐巨妖",
    "guardian_golem": "废墟魔像",
    "guardian_totem": "废墟守卫·火",
    "owl": "维·索拉斯",
    "dorsal_brothers": "背鳍三兄弟",
    # future
    "stella": "史黛拉",
    "light": "莱特",
    "white_tiger_story": "white_tiger_story",
    "child_soldier": "child_soldier",
    "loran": "罗兰",
    "load_of_sand": "沙漠领主",
    "stella_copy": "stella_copy",
    "pirates_a": "海盗A",
    "pirates_b": "海盗B",
    "boss_pirates_captain": "海盗船长",
    "dog_king": "犬族之王",
    "elder_cat": "猫长老",
    "sing_android_unknown": "蒂亚_unknown",
    "alpha_android": "阿尔法",
    "beta_android": "贝塔",
    "broken_android": "坏掉的机人",
    "admin_human": "管理者(人)",
    "admin_human_unknown": "管理者(人)_unknown",
    "onmyoji_boy_unknown": "水善_unknown",
    "big_orga": "大鬼",
    "mob_onmitsu": "护卫",
    "little_fox": "穿和服的狐狸",
    "flame_witch_known": "红发老战士",
    "flame_witch": "夏可缇",
    "golden_dragon": "拉夫马诺",
    "refugees_boy": "艾力克",
    "elf_princess_unknown": "艾丝缇莉艾尔_unknown",
    "devil_ylbis": "伊尔比斯",
    "devil_commander": "伊尔比斯",
    "devil_commander_unknown": "伊尔比斯_unknown",
    "devil_leader_unknown": "艾迪凯斯_unknown",
    "maou": "魔王",
    "devil_sismama": "梅莉",
    "light_origin": "勇者莱特",
    "guild_exective": "多·库库斯",
    "nova": "诺瓦",
}
# 如果name和filename不同，则添加到下面
filenames = {
    "領主の少年?ローラン": "少年领主",
    "stella_copy_known": "面具术士",
    "stella_copy_mask_off": "史黛拉？",
    "devil_commander_known": "魔族男性",
    "devil_commander_unknown": "？？？",
    "gaunt_women": "消瘦的女子",
    "old_mermaid_man_known": "爷爷",
    "refugees_boy_known": "难民男孩",
    "refugees_women": "难民女子",
    "refugees_child": "难民小孩",
    "refugees_man": "难民男子",
    "knight_leaders": "干部青年",
    "knight_length_mob": "骑士长",
    "knight_mob": "骑士",
    "soldier_mob": "士兵",
    "guard_man": "警卫兵",
    "elf_princess_disguise_unknown": "？？？",
    "elf_princess_disguise_known": "精灵少女",
    "elf_princess_disguise": "莉艾尔",
    "tree_people": "木桩",
    "elf_warrior_unknown": "？？？",
    "elf_warrior": "精灵战士",
    "elf_princess_known": "莉艾尔？",
    "elves_voice_only": "精灵们的声音",
    "refugees_mob": "难民",
    "crude_man": "粗鲁的人",
    "gloomy_man": "阴郁的人",
    "devil_sismama_unknown": "？？？",
    "demons_people": "魔族",
    "demons_soldier": "魔族之兵",
    "victory_voice": "战斗声",
    "demons_executive": "魔族干部",
    "flame_witch_known": "夏可缇",
    "devil_commander_known": "伊尔比斯",
    "gaunt_women": "",
    "old_mermaid_man_known": "",
    "refugees_boy_known": "艾力克",
    "refugees_women": "",
    "refugees_child": "",
    "refugees_man": "",
    "knight_leaders": "",
    "knight_length_mob": "",
    "knight_mob": "",
    "soldier_mob": "",
    "guard_man": "",
    "elf_princess_disguise_unknown": "",
    "elf_princess_disguise_known": "", # 莉艾尔
    "elf_princess_disguise": "",
    "tree_people": "",
    "devil_leader_known": "",
    "devil_leader_known2": "艾迪凯斯",
    "elf_warrior_unknown": "",
    "elf_warrior": "",
    "elf_princess_known": "艾丝缇莉艾尔",
    "elves_voice_only": "",
    "refugees_mob": "",
    "crude_man": "",
    "gloomy_man": "",
    "devil_sismama_unknown": "梅莉",
    "devil_ylbis": "伊尔比斯_ylbis",
    "demons_people": "",
    "demons_soldier": "",
    "victory_voice": "",
    "demons_executive": "",
}
# 技能名
skillnames = {
    "atk_all_direction": "朝不同方向攻击",
    "atk_surround": "攻击自己周围区域",
    # "atk_back": "",
    "atk_common": "攻击",
    "atk_field": "领域全体效果",
    "atk_four_ranges": "上下左右方向攻击",
    "atk_four_ranges_cross": "对角线方向攻击",
    "atk_front": "前进攻击",
    "atk_front_back": "前后方向攻击",
    "atk_go_direction": "行进方向攻击",
    "atk_hit": "对击中的敌人有效",
    "atk_nearest": "攻击最近的敌人",
    "fever": "FEVER槽提升",
    "flip": "强化弹射伤害上升",
    "float": "浮游",
    "heal": "治疗",
    "invincible": "无敌",
    "multi_ball": "协力球",
    "multi_bomb": "炸弹协力球",
    "penet": "贯穿",
    "poison": "中毒",
    "regene": "再生",
    "resist": "弱体抗性上升",
    "resist_up_purple": "暗属性抗性上升",
    "resist_up_red": "火属性抗性上升",
    "resist_up_white": "光属性抗性上升",
    "skill_str_up": "技能伤害上升",
    "str_up": "攻击力上升",
}
# 属性
attrs = {
    "0": "火",
    "1": "水",
    "2": "雷",
    "3": "风",
    "4": "光",
    "5": "暗",
    "6": "无",
}
# 种族
races = {
    "Human": "人",
    "Element": "精灵",
    "Devil": "魔",
    "Beast": "兽",
    "Machine": "机械",
    "Mystery": "妖",
    "Dragon": "龙",
    "Undead": "不死",
    "Aquatic": "水栖",
    "Plants": "植物",
}
# 性别
genders = {
    "Male": "男",
    "Female": "女",
    "Ririi": "莉莉",
    "Unknown": "不明",
}
# 类型
_types = {
    "1": "格斗",
    "0": "剑士",
    "2": "射击",
    "3": "辅助",
    "4": "特殊",
}
# 职责
stances = {
    "Attacker": "进攻",
    "Tank": "防护",
    "Healer": "治疗",
    "Supporter": "支援",
    "Jammer": "妨碍",
    "Balance": "平衡",
}
def en2cn(en):
    en = en.replace(".png", "").replace(".jpg", "")
    return names.get(en, "")

def en2f(en):
    en = en.replace(".png", "").replace(".jpg", "")
    return filenames.get(en, names.get(en, ""))

def en2skill(en):
    en = en.split("/")[-1]
    return skillnames.get(en, en)

def en2attr(en):
    return attrs.get(en, en)

def en2race(en):
    en = en.split(",")
    return ",".join([races.get(_, _) for _ in en])

def en2gender(en):
    return genders.get(en, en)

def en2type(en):
    return _types.get(en, en)

def en2stance(en):
    return stances.get(en, en)

def story_no_chapter():
    wf = open("en2cn.txt", "w+", encoding="utf-8")
    with open("en.txt", "r", encoding="utf-8") as rf:
        line = rf.readline()
        while line:
            line = line.replace("\n", "").replace("\\n", "<br>").split("\t")
            cn = en2cn(line[0])
            f = en2f(line[1])
            if cn == "":
                wf.write("{{对话||" + line[0] + "|" + line[1] + "}}\n")
            else:
                wf.write("{{对话|" + f + "|" + cn + "|" + line[1] + "}}\n")
            line = rf.readline()
    wf.close()

def story_with_chapter():
    chapter = open("enChapter.txt", "r", encoding="utf-8")
    wf = open("en2cn.txt", "w+", encoding="utf-8")
    idx = "00"
    with open("en.txt", "r", encoding="utf-8") as rf:
        line = rf.readline()
        while line:
            line = line.replace("\n", "").replace("\\n", "<br>").split("\t")
            if line[1] == "1":
                line = rf.readline()
                continue
            if idx != line[0]: # new chapter
                idx = line[0]
                c = chapter.readline()
                c = c.replace("\n", "").replace("\\n", "<br>").split("\t")
                wf.write("==" + c[0] + "==\n")
                wf.write("{{折叠|宽度=100%\n")
                wf.write("|标题=剧情梗概\n")
                wf.write("|内容=" + c[1] + "\n")
                wf.write("}}\n")
            cn = en2cn(line[1])
            f = en2f(line[1])
            if cn == "":
                wf.write("{{对话||" + line[1] + "|" + line[2] + "}}\n")
            else:
                wf.write("{{对话|" + f + "|" + cn + "|" + line[2] + "}}\n")
            line = rf.readline()
    wf.close()

if __name__ == "__main__":
    # story
    story_with_chapter()