# 英文名转为中文名
names = {
    "alk": "阿尔克",
    "white_tiger": "白",
    "fire_dragon": "瓦格纳",
    "pirates_girl": "玛丽娜",
    "clarisse": "克拉莉丝",
    "brown_fighter": "索妮雅",
    "onmyoji_boy": "水善",
    "fox_oracle": "稻穗",
    "cagliostro": "卡莉奥丝特罗",
    "wind_spgirl": "希尔媞",
    "wind_oracle": "菲莉亚",
    "katana_ghost": "丛云",
    "mercenary": "雷恩",
    "ruin_girl": "奈芙提姆",
    "prince_zero": "拉杰尔特",
    "bodysuit_trooper": "艾可莉儿",
    "dimension_witch": "贝尔赛蒂亚",
    "veteran_hunter": "威隆",
    "dragon_slayer": "阿赛尔",
    "lady_summoner": "碧安卡",
    "kunoichi": "花火",
    "half_oni_boy": "阿须桐丸",
    "master_knight": "格莱德",
    "swallow_knight": "尤维尔",
    "bishop_girl": "莉洁儿",
    "mermaid": "亚美莉亚",
    "alice": "爱丽丝",
    "battle_guild_staff": "夏农",
    "spry_sailor": "拉纳",
    "thunder_dragon": "拉姆斯",
    "fox_scientist": "露娜露",
    "rec_android": "雷吉斯",
    "elf_soldier": "艾琳诺儿",
    "cat_shaman": "杰",
    "minotaur_girl": "米诺",
    "tiger_treasure_hunter": "米娅",
    "birdman": "奥罗尔",
    "samurai": "宗士郎",
    "elf_archer": "梅露希儿",
    "dog_slasher": "赫尔加",
    "sing_android": "蒂亚",
    "unicorn_lancer": "杰拉尔",
    "lightbullet_wiz": "艾莉亚",
    "palpebra_knight": "芬",
    "palpebra_knight_lady": "绮拉",
    "devil_princess": "阿露姆",
    "battle_maid": "玛丽安",
    "undead_boy": "安迪",
    "warlock": "里昂",
    "alchemist": "莉莉露",
    "pretty_witch": "梅米",
    "gunslinger": "伊莉斯",
    "monster_hunter": "哈修",
    "black_doctor": "仁",
    "cool_woman_soldier": "特蕾涅",
    "berserker": "吉斯拉多",
    "fire_shaman": "恩妮",
    "disciplined_swordman": "杰克",
    "sniper": "凯洛斯",
    "urban_soldier": "崔丝塔",
    "hard_face_soldier": "瓦尔塔",
    "nurse": "艾尔莎",
    "wolf_assassin": "克劳斯",
    "fox_companion": "白乃",
    "depraved_monk": "诲谕",
    "sailor_girl": "拉蒂",
    "cute_fafnir": "法夫",
    "mens_attire_girl": "莉可",
    "twin_blader": "优娜",
    "bee_girl": "赫妮",
    "lightning_fighter": "泰加",
    "outlaw_panther": "黑",
    "wolf_swordsman": "阿尔伯特",
    "oni_girl": "加津知",
    "sociable_mestizo": "泰奇安娜",
    "magic_boy": "科特",
    "student_gunsmith": "夏·丝丝",
    "highlander": "伊凡",
    "dryad": "茶露亚",
    "lich": "瑞西塔尔",
    "casino_dealer": "奈丝卡",
    "cat_fighter": "缪",
    "devil_clown": "菲勒斯",
    "herbalist": "荷莉",
    "spearman": "科那",
    "trap_errand": "贾斯塔",
    "priest": "可莉娜",
    "lady_gunner": "玛格丽特",
    "woman_knight": "赛希莉亚",
    "docking_beast": "欧雷欧",
    "exorcist_oldman": "劳尔",
    "half_knight": "米雷斯",
    "reporter": "璐璐卡",
    "reaper_girl": "法露伽",
    "chakram_shooter": "札里尔",
    "devil_woman_soldier": "厄莉",
    "informant": "紫苑",
    "arabic_swordman": "阿迪尔",
    "dark_nursemaid": "桃乐西亚",
    "bearish_darkwitch": "蕾贝卡",
    "guardian_golem": "魔像",
    "owl": "波吉特",
    "fox": "镰鼬",
    "kinoko": "蘑仔",
    "slango_red": "红波露",
    "spirit_fire": "火精",
    "slango_blue": "蓝波露",
    "slango_yellow": "黄波露",
    "paralysis_hedgehog": "帕拉鼠",
    "slango_green": "绿波露",
    "arisa": "亚里莎",
    "battle_maid_xm19": "玛丽安(圣诞)",
    "samurai_xm19": "宗士郎(圣诞)",
    "fox_oracle_xm19": "稻穗(圣诞)",
    "red_gunner": "卡农",
    "docking_beast_xm19": "欧雷欧(圣诞)",
    "fortuneteller": "芙拉",
    "dryad_xm19": "茶露亚(圣诞)",
    "heavenly_one": "诺埃妮",
    "lightbullet_wiz_ny20": "艾莉亚(新年)",
    "reporter_ny20": "璐璐卡(新年)",
    "bearish_darkwitch_ny20": "蕾贝卡(新年)",
    "swallow_knight_ny20": "尤维尔(新年)",
    "wild_wolfgirl": "加萝",
    "cat_fighter_ny20": "缪(新年)",
    "sword_beauty": "葵泽",
    "ice_witch": "赛法",
    "blade_witch": "莫弥亚",
    "black_hair_swordman": "阿德尼",
    "gang_girl": "凯特",
    "compliment_oiran": "菊野",
    "thunder_archer": "梅媞斯",
    "shapely_soldier": "蕾维",
    "beast_adventurer": "露",
    "birdwoman": "可兰",
    "monster_cook": "帕尔菲",
    "commander": "希丽奴",
    "bigwing_shaman": "西微",
    "deepsea_mage": "萨尔",
    "monster_attract": "诺塞尔",
    "black_wolf_knight": "罗尔夫",
    "mighty_striker": "巴拉克",
    "timid_kunoichi": "凉风",
    "illusionist": "伊路米",
    "starbreak_hunter": "塔吉斯",
    "combat_soldier": "贝瑞塔",
    "desert_wizard": "莫迪亚迦",
    "unleash_hunter": "霍普",
    "touyakiren_ceo": "拉芙",
    "lakeside_guardian": "里姆尼斯",
    "cursed_girl": "卡菈",
    "lady_android": "露迪",
    "unyielding_adventurer": "莱亚",
    "delusion_girl": "梅利露",
    "gentle_barten": "米格里",
    "tengu_girl": "小羽",
    "whitedog_beast": "芙洛丽塔",
    "junior_yearngirl": "克菈菈",
    "drawing_witch": "拉绮夏",
    "blade_dancer": "里布拉姆",
    "onmyo_attendant": "蛟",
    "blindness_gunner": "赛吉尔",
    "old_mercenary": "卑尔根",
    "machine_police_girl": "塞拉",
    "crybaby_shooter": "琪丽",
    "psycho_reaper": "索维",
    "tradition_healer": "哈丽莎",
    "kokkoro": "可可萝",
    "pecorine": "佩可莉姆",
    "kyaru": "凯露",
    "sanctuary_guard": "米尔米娜",
    "brave_mouse": "斯文",
    "big_gunner": "牡丹",
    "ruin_girl_halfanv": "奈芙提姆(礼服)",
    "olivia": "奥莉维尔",
    "pirates_gunner": "贝伊斯",
    "luna": "露娜",
    "little_shaman": "纱玛莎",
    "fake_princess": "普莉卡",
    "dimension_witch_smr20": "贝尔赛蒂亚(泳装)",
    "wind_dragon": "休尔特",
    "hidden_blader": "罗塞莉亚",
    "keylock_girl": "琪亚娜",
    "scout_girl": "莉塔",
    "prince_zero_smr20": "拉杰尔特(泳装)",
    "magic_sword_girl": "娜希尔",
    "dinosaur_hunter": "格里格",
    "moth_girl": "摩菈",
    "pirates_girl_smr20": "玛丽娜(泳装)",
    "tiger_treasure_hunter_smr20": "米娅(泳装)",
    "illusionist_smr20": "伊路米(泳装)",
    "casino_dealer_smr20": "奈丝卡(泳装)",
    "bishop_girl_smr20": "莉洁儿(泳装)",
    "lazy_genious": "涅迪",
    "neoviolin_musician": "莉菈",
    "alice_smr20": "爱丽丝(泳装)",
    "unicorn_lancer_smr20": "杰拉尔(泳装)",
    "lady_gunner_smr20": "玛格丽特(泳装)",
    "floating_girl": "芙拉娜",
    "high_priestess": "奥薇尔",
    "lamp_guide": "菲拉梅里亚",
    "vigilante_boy": "仓丸",
    "crazy_doctor": "布莱斯",
    "minamoto_sakura": "源樱",
    "nikaido_saki": "二阶堂咲",
    "yugiri": "夕雾",
    "yamada_tae": "山田多惠",
    "hoshikawa_ririi": "星川莉莉",
    "konno_junko": "绀野纯子",
    "mizuno_ai": "水野爱",
    "ekaki_onmyoji": "鹄",
    "sing_android_hw20": "蒂亚(万圣)",
    "fox_scientist_hw20": "露娜露(万圣)",
    "reaper_girl_hw20": "法露伽(万圣)",
    "priest_hw20": "可莉娜(万圣)",
    "dark_psygirl": "蒂妮",
    "sorceress_teacher": "妮可拉",
    "wild_boy": "哈奥",
    "illegal_herbalist": "塞尔玛",
    "elf_princess": "艾丝缇莉艾尔",
    "freeze_eye": "雷拉斯",
    "junior_soldier": "可莎",
    "devil_leader": "艾迪凯斯",
    "resistance_princess": "莉莉丝",
    "rec_android_1anv": "雷吉斯(周年)",
    "shy_assassin": "薇薇",
    "doctor_machine": "梅克",
    "sewing_girl": "莉莉安",
    "silent_ninja": "八云",
    "kunoichi_1anv": "花火(周年)",
    "wind_spgirl_1anv": "希尔媞(周年)",
    "wind_oracle_1anv": "菲莉亚(周年)",
    "woman_knight_1anv": "赛希莉亚(周年)",
    "devil_woman_soldier_1anv": "厄莉(周年)",
    "alk_1anv": "阿尔克(周年)",
    "lady_summoner_xm20": "碧安卡(圣诞)",
    "devil_princess_xm20": "阿露姆(圣诞)",
    "cool_woman_soldier_xm20": "特蕾涅(圣诞)",
    "black_hair_swordman_xm20": "阿德尼(圣诞)",
    "delusion_girl_xm20": "梅利露(圣诞)",
    "white_tiger_xm20": "白(圣诞)",
    "heavenly_two": "布茜",
    "timid_kunoichi_ny21": "凉风(新年)",
    "urban_soldier_ny21": "崔丝塔(新年)",
    "little_wizard": "托·蕾蕾妮",
    "lightbullet_wiz_vt21": "艾莉亚(情人节)",
    "whitedog_beast_vt21": "芙洛丽塔(情人节)",
    "halberd_princess": "托莉亚",
    "combat_animal": "芙拉菲",
    "wind_striker": "里卡尔德",
    "sea_violent": "蒂蕾特",
    "emilia": "爱蜜莉雅",
    "rem": "雷姆",
    "ram": "拉姆",
    "subaru": "菜月·昴",
    "doctor_pirate": "燎",
    "girl_and_mecha": "洛蒂",
    "punk_warrior": "艾蒂塔",
    "mystery_agent": "爱德华",
    "waterdragon_kunfu": "谢胧",
    "summoner_little": "珂艾特",
    "steel_lacrosse": "米迪",
    "skateboard_boy": "阿克塞姆",
    "onmyoji_boy_wt21": "水善(白情)",
    "wolf_assassin_wt21": "克劳斯(白情)",
    "crystal_swordman": "塞里奥尔",
    "noble_sorceress": "梅尔维奥拉",
    "electro_girl": "特尔娜",
    "desert_commander": "哈里达尔",
    "brown_fighter_dst21": "索妮雅(沙漠)",
    "dark_psygirl_dst21": "蒂妮(沙漠)",
    "kids_gunner": "鲁·鲁特",
    "ruin_lady": "索媞艾丝",
    "magical_bayonetter": "克亚雷",
    "general_toyakiren": "兹茵可",
    "walking_armor": "伦达尔",
    "beast_shaman": "涅维亚",
    "mummy_boy": "塔尔哈",
    "zeta": "塞达",
    "beatrix": "贝阿朵丽丝",
    "secret_observer": "吉泽尔",
    "desert_caravans": "塔维尔",
    "samurai_robot": "斩铁",
    "yokai_exterminator": "莲月",
    "cool_witch_girl": "皮亚莫",
    "sleep_puppy": "菲妮",
    "mermaid_1halfanv": "亚美莉亚(礼服)",
    "elf_princess_1halfanv": "艾丝缇莉艾尔(礼服)",
    "blindness_gunner_1halfanv": "赛吉尔(礼服)",
    "naginata_girl": "舞姬",
    "revenge_rabbit": "科迪",
    "hero_girl": "涅特",
    "tsundere_bountyhunter": "蕾缇希娅",
    "elder_guild_fighter": "玛奇斯",
    "stylish_witch": "珐颂",
    "desert_priest": "萨莉哈",
    "holy_mother": "玛姆娜莉亚",
    "machine_police_girl_smr21": "塞拉(泳装)",
    "resistance_princess_smr21": "莉莉丝(泳装)",
    "dragon_slayer_smr21": "阿赛尔(泳装)",
    "rookie_adventurer": "米蕾特",
    "bodysuit_trooper_smr21": "艾可莉儿(泳装)",
    "blackflower_wiz": "普莉姆拉",
    "dress_gunner": "艾芙琳",
    "bird_master": "路马尔克",
    "tengu_master": "豪岚",
    "bigwing_shaman_smr21": "西微(泳装)",
    "fox_oracle_smr21": "稻穗(泳装)",
    "fox_companion_smr21": "白乃(泳装)",
    "psycho_reaper_smr21": "索维(泳装)",
    "assistant_boy": "露西尔",

    "suzumiya_haruhi": "凉宫春日",
    "nagato_yuki": "长门有希",
    "asahina_mikuru": "朝比奈实玖瑠",
    "kyon": "阿虚",
    "koizumi_ituki": "古泉一树",

    "mercenary_smr21": "雷恩(浴衣)",
    "ruin_girl_smr21": "奈芙提姆(浴衣)",
    "formercorrupt_detective": "薇尔吉娅",
    "conjurer_girl": "菲·诺诺亚",
    "cyber_battergirl": "丝特莱纳",
    "horn_leader": "梅姆拉姆",
    "guildknight_leader": "泽赫尔",
    "warashi": "阿福",
    "waterdragon_kunfu_proud": "谢胧(百兽)",
    "dog_slasher_proud": "赫尔加(百兽)",
    "lion_boy": "提欧",
    "pilgrim_monk": "玛卡妮",
    "neoviolin_musician_hw21": "莉菈(圣诞)",
    "touyakiren_ceo_hw21": "拉芙(圣诞)",
    "spry_sailor_hw21": "拉纳(圣诞)",
    "sanctuary_guard_hw21": "米尔米娜(圣诞)",
    "psychic_yuki": "见岛勇希",
    "psychic_shouta": "伊野里翔太",
    "psychic_tomboygirl": "绯河凛音",
    "psychic_nao": "凪原直",
    "psychic_seiji": "鹰森诚司",
    "shadow_redhood": "琉农",
    "navy_officer": "芙拉克西斯",
    "psychic_tohru": "千岳十织",
    "psychic_projection": "影丘龙一",
    "pirates_girl_2anv": "玛丽娜(周年)",
    "summoner_little_2anv": "珂艾特(周年)",
    "stella_2anv": "史黛拉(周年)",
    "informant_2anv": "紫苑(周年)",
    "ice_witch_2anv": "赛法(周年)",
    "white_tiger_2anv": "白(周年)",
    "nurse_pirate": "皮西卡",
    "freeze_eye_xm21": "雷拉斯(圣诞)",
    "combat_animal_xm21": "芙拉菲(圣诞)",
    "devil_clown_xm21": "菲勒斯(圣诞)",
    "heavenly_three": "特拉埃蒂",
    "high_priestess_ny22": "奥薇尔(新年)",
    "dimension_witch_ny22": "贝尔赛蒂亚(新年)",
    "shapely_soldier_ny22": "蕾维(新年)",
    "outlaw_panther_ny22": "黑(新年)",
    "misogi": "未奏希",
    "kyouka": "镜华",
    "mimi": "美美",
    "tsundere_bountyhunter_vt22": "蕾缇希娅(情人节)",
    "hero_girl_vt22": "涅特(情人节)",
    "spanner_girl": "艾蕾吉娅",
    "sheep_girl": "梅莉安娜",
    "ice_dragon": "安巴赫",
    "super_robot": "特克托",
    "marching_conductor": "玛露琪亚",
    "wind_dragon_wt22": "休尔特(白情)",
    "katana_ghost_wt22": "丛云(白情)",
    "advanced_soldier": "卡菈薇娜",
    "justice_lady": "贾丝缇",
    "still_obstinator": "丝缇涅尔",
    "pbc_operator": "克拉尔缇",
    "anger_investigator": "威弗",
    "estateguild_leader": "希尔狄嘉德",
    "scissor_ratgirl": "琳卡莉娜",
    "airship_captain": "奎茵薇德",
    "mirror_witch": "路易莉兹",
    "long_hair_swordsman": "奥涅斯特",
    "spider_ninja": "茧月",
    "waste_armor": "艾尔玛露",
    "innocent_glaiver": "珐洛洛",
    "halberd_princess_2halfanv": "托莉亚(周年)",
    "sing_android_2halfanv": "蒂亚(周年)",
    "warlock_2halfanv": "里昂(周年)",
    "student_president": "露西娅妲",
    "gold_ship": "黄金船",
    "silence_suzuka": "无声铃鹿",
    "special_week": "特别周",
    "megumin": "惠惠",
    "aqua": "阿库娅",
    "darkness": "达克妮斯",
    "kazuma": "和真",
    "monster_cook_smr22": "帕尔菲(泳装)",
    "psychic_shouta_smr22": "伊野里翔太(泳装)",
    "nurse_pirate_smr22": "皮西卡(泳装)",
    "twin_blader_smr22": "优娜(泳装)",
    "combat_soldier_smr22": "贝瑞塔(泳装)",
    "samurai_robot_smr22": "斩铁(泳装)",
    "blackflower_wiz_smr22": "普莉姆拉(泳装)",
    "rural_ladyship": "艾可",
    "luca_playable": "卢卡",
    "nihilist_mechgirl": "拉普缇娜",
    "sand_bandit": "法拉",
    "lion_swordman_playable": "玛格诺斯",
    "psychic_yamikawa": "操里缘子",
    "ekaki_girl_playable": "凉月",
    "little_vampire": "露米拉卡",
    "holysword_girl": "伊莉诺雅",
    "marching_rival": "埃尔梅丽莎",
    "golemclub_captain": "黛妲莉亚",
    "pirates_of_fear": "泽利米尔",
    "ghost_nymph": "真乃香",
    "palpebra_knight_lady_hw22": "绮拉(万圣)",
    "wind_spgirl_hw22": "希尔媞(万圣)",
    "psychic_tomboygirl_hw22": "绯河凛音(万圣)",
    "noelle_silva": "诺艾尔·希尔巴",
    "yuno": "由诺",
    "asta": "阿斯塔",
    "asymmetry_birdgirl": "泽菲尔",
    "horn_mypace": "埃尔摩尔",
    "kung_fu_girl": "芙兰",
    "wind_spbro_3anv": "夏尔(流星祭)",
    "swallow_knight_3anv": "尤维尔(流星祭)",
    "veteran_hunter_3anv": "威隆(流星祭)",
    "rector_sorcerer_playable": "尼尔娅娜(流星祭)",
    "reformist_prince": "瓦雷因",
    "tiger_treasure_hunter_xm22": "米娅(圣诞)",
    "compliment_oiran_xm22": "菊野(圣诞)",
    "herbalist_xm22": "荷莉(圣诞)",
    "psychic_yuki_ny23": "见岛勇希(新年)",
    "general_toyakiren_ny23": "兹茵可(新年)",
    "heavenly_four": "希尔克哈蕾(新年)",
    "dark_psygirl_vt23": "蒂妮(情人节)",
    "heavenly_two_vt23": "布茜(情人节)",
    "sleep_puppy_vt23": "菲妮(情人节)",
    "octcyborg_lady": "卡西瓦卢斯",
    "evilloli_master": "塔娜奇艾拉",
    "jiangshi_girl": "江诗",
    "still_obstinator_ballot23": "斯蒂内尔(流星祭)",
    "light_ballot23": "莱特(流星祭)",
    "stella_ballot23": "史黛拉(流星祭)",
    "flame_blessgirl": "露涅塔",
    "psychic_gal": "朝户八重",
    "impostor_priest": "伊奥雷斯",
    "blade_dancer_wt23": "里布拉姆(白情)",
    "black_wolf_knight_wt23": "罗尔夫(白情)",
    "hero_mechanic": "因维特拉",
    "ruin_lady_meteor23": "索媞艾丝(流星祭)",
    "pbc_ceo_playable": "K·约翰逊(流星祭)",
    "wind_oracle_meteor23": "菲莉亚(流星祭)",
    
    "guild_front_girl": "普·莉莉艾",
    "merchant": "玛·露露夏",
    # boss
    "multi_battle_pickup_empress": "青之女王",
    # "white_tiger_ghost": "白虎",
    "white_tiger_ghost": "白虎的亡灵",
    # "lich": "不死王瑞西塔尔",
    "lich": "瑞西塔尔",
    "treant": "雷霆树妖",
    "orochi": "八岐大蛇",
    "ghost_fox": "狐妖",
    "administrator": "管理者",
    "security_armor": "Sec-5200Li",
    "boar_rider": "风将獠牙骑士",
    "arch_evil": "诅咒弧魔艾基尔",
    "hermit_crab": "寄居蟹船长",
    "kraken": "潮汐巨妖",
    "guardian_golem": "废墟魔像",
    "guardian_totem": "废墟守卫·火",
    "owl": "维·索拉斯",
    "dorsal_brothers": "背鳍三兄弟",
    "evil_envy": "艾基尔·嫉妒",
    # future
    "stella": "史黛拉",
    "light": "莱特",
    "white_tiger_story": "white_tiger_story",
    "child_soldier": "child_soldier",
    "loran": "罗兰",
    "load_of_sand": "沙漠领主",
    "stella_copy": "stella_copy",
    "pirates_a": "海盗A",
    "pirates_b": "海盗B",
    "boss_pirates_captain": "海盗船长",
    "dog_king": "犬族之王",
    "elder_cat": "猫长老",
    "sing_android_unknown": "蒂亚_unknown",
    "alpha_android": "阿尔法",
    "beta_android": "贝塔",
    "broken_android": "坏掉的机人",
    "admin_human": "管理者(人)",
    "admin_human_unknown": "管理者(人)_unknown",
    "onmyoji_boy_unknown": "水善_unknown",
    "big_orga": "大鬼",
    "mob_onmitsu": "护卫",
    "little_fox": "穿和服的狐狸",
    "flame_witch_known": "红发老战士",
    "flame_witch": "夏可缇",
    "golden_dragon": "拉夫马诺",
    "refugees_boy": "艾力克",
    "elf_princess_unknown": "艾丝缇莉艾尔_unknown",
    "devil_ylbis": "伊尔比斯",
    "devil_commander": "伊尔比斯",
    "devil_commander_unknown": "伊尔比斯_unknown",
    "devil_leader_unknown": "艾迪凯斯_unknown",
    "maou": "魔王",
    "devil_sismama": "梅莉",
    "light_origin": "勇者莱特",
    "guild_exective": "多·库库斯",
    "nova": "诺瓦",
    "psychic_sakuya": "星乃咲夜",
    "psychic_mikoto": "星乃命",
    "boy_alk": "凪原步",
    # "seimei_staff": "星命会信者",
    # "sorcerer": "魔法师",
    "seimei_staff": "seimei_staff",
    "sorcerer": "sorcerer",
    "psychic_sakuya_unknown": "星乃咲夜_unknown",
    "psychic_shouta_unknown": "伊野里翔太_unknown",
    "psychic_projection_unknown": "影丘龙一_unknown",
    "white_tiger_unknown": "白_unknown",
    "sorcerer_unknown": "sorcerer_unknown",
    "stella_copy_unknown": "stella_copy_unknown",

    # equip
    "main_chapter_orb_1": "精灵的微笑",
    "main_chapter_orb_2": "沙海的友情",
    "main_chapter_orb_3": "女海盗的盛宴",
    "main_chapter_orb_4": "爪牙之交",
    "main_chapter_orb_5": "歌姬之声",
    "main_chapter_orb_6": "人妖百鬼夜行",
    "main_chapter_orb_7": "炎之信赖",
    "main_chapter_orb_8": "传承之物",
    "main_chapter_orb_9": "逆天而行的决意",
    "main_chapter_orb_10": "伸出你的手",
    "main_chapter_orb_11": "黄金之路",
    "practice_trophy_1": "超越守护之证",
    "practice_trophy_2": "超越诅咒之证",
    "practice_trophy_3": "超越强度之证",
    "practice_trophy_4": "超越速度之证",
    "practice_trophy_5": "超越硬度之证",
    "trophy_maou_hunt": "清剿之证",
    "non_playable_equipment_1": "破星剑",
    "non_playable_equipment_2": "破星剑",
    "sword_0001": "老旧短剑",
    "staff_0001": "老旧法杖",
    "shield_0001": "老旧盾牌",
    "sword_0002": "无名长剑",
    "axe_0001": "无名之斧",
    "spear_0001": "无名之枪",
    "bow_0001": "无名之弓",
    "book_0001": "无名古书",
    "fist_0001": "无名拳具",
    "sword_0006": "流转之剑",
    "sword_0007": "短弯刀",
    "sword_0008": "玻璃之刃",
    "sword_0013": "焰形剑",
    "sword_0023_april": "幻想的胡萝卜剑",
    "sword_0027": "闪电匕首",
    "sword_0035": "高热剑",
    "sword_0053": "野营刀",
    "axe_0003": "战士之斧",
    "axe_0006": "战争巨镰",
    "axe_0011": "维京斧",
    "axe_0012": "牛斧",
    "spear_0006": "流转之枪",
    "spear_0007": "步兵长矛",
    "spear_0012": "长柄刀",
    "spear_0013": "偃月刀",
    "spear_0027": "激光标枪",
    "bow_0003": "长弓",
    "bow_0006": "十字弓",
    "bow_0032": "投石机",
    "book_0002": "罗洪特写本",
    "book_0005": "谎言之书",
    "book_0010": "斐莱布篇",
    "staff_0002": "流转之杖",
    "staff_0003": "司祭之杖",
    "staff_0007": "魔术手杖",
    "staff_0010": "战士棍棒",
    "fist_0006": "半月拳刃",
    "fist_0010": "龙之拳套",
    "fist_0018": "黄铜拳套",
    "fist_0022": "混沌指虎",
    "shield_0002": "战士之盾",
    "shield_0008": "青金石盾",
    "shield_0009": "骑士盾",
    "shield_0017": "空气反应炉",
    "acce_0036": "紫藤耳坠",
    "gun_0007": "虹彩起爆器",
    "sword_0003": "妖刀蛇崩",
    "sword_0010": "伊文剑",
    "sword_0014": "木灵大剑",
    "sword_0015": "祸根之剑",
    "sword_0017": "贝帝之剑",
    "sword_0018": "断罪之剑",
    "sword_rare4_phl_blade": "PHL光剑",
    "sword_0024_coop": "七支铜刀",
    "sword_0048_raid_revival": "灼炎龙剑",
    "sword_0049_raid_revival": "水蚀龙鞭",
    "sword_0052_raid_revival": "凶暗龙刃",
    "sword_0071_storyevent": "无暇灵剑",
    "axe_0007": "印第安战斧",
    "axe_0013": "古代战斧",
    "axe_0014": "狐影之斧",
    "axe_0016": "诅咒之斧",
    "axe_0019_coop": "名匠之槌",
    "axe_0021_storyevent": "黄金耙",
    "axe_0033_boss_unique": "巨斧",
    "axe_0034_raid_revival": "黑龙雷斧",
    "spear_0003": "标枪",
    "spear_0004": "螺旋长枪",
    "spear_0008": "游击者",
    "spear_0009": "珊瑚之枪",
    "spear_0014": "毁灭者",
    "spear_0019": "黑龙雷枪",
    "spear_0024": "风车",
    "spear_0032_storyevent": "王国兵制式长枪",
    "bow_0007": "合成弓",
    "bow_0008": "梓弓",
    "bow_0012": "玄虎之弓",
    "bow_0021": "旋涡之弓",
    "bow_0023_coop": "祈愿之弓",
    "bow_0024_raid": "歼风龙弓",
    "bow_0027_boss_unique": "猎弓",
    "bow_0034_raid": "传焰弦",
    "book_0004": "战国策写本",
    "book_0007": "尼伯龙根之歌",
    "book_0011": "石兵要术",
    "book_0019_coop": "海盗兵法",
    "book_0021_storyevent": "百物语",
    "book_0023_raid": "万圣日志",
    "book_0030_raid": "偏执狂",
    "book_0031_raid_revival": "光芒龙典",
    "staff_0005": "神圣之杖",
    "staff_0011": "百妖花杖",
    "staff_0022": "血脉之杖",
    "staff_0023_raid": "凶暗龙杖",
    "staff_0028": "熔岩长杖",
    "staff_0031_raid_revival": "歼风龙杖",
    "staff_0032": "启明之杖",
    "staff_0035": "高洁之伞",
    "staff_0036_storyevent": "真理之泪",
    "fist_0004": "赤鬼手套",
    "fist_0007": "强力拳",
    "fist_0011": "大乌贼爪",
    "fist_0012": "兽王牙拳",
    "fist_0016_raid": "灼炎龙拳",
    "fist_0031_storyevent": "虚假克隆",
    "fist_0034_storyevent": "狮子笼手",
    "fist_0037_storyevent": "战火人偶",
    "fist_0038_raid": "无爱拳",
    "fist_0041_raid": "拓枪爪",
    "shield_0003": "钻石盾",
    "shield_0015": "林德虫之盾",
    "shield_0016_raid": "光芒龙盾",
    "shield_0019": "四向巴纹盾",
    "shield_0021": "噪声划痕盾",
    "shield_0023_storyevent": "JIT盾",
    "shield_0024_raid": "因果理",
    "shield_0027": "暴击大盾",
    "acce_0006_storyevent": "钥匙挂坠",
    "acce_0012_storyevent": "典礼勋章",
    "acce_0033_boss_unique": "怨嗟逆饰",
    "acce_0037_raid": "月宫环",
    "acce_0043_storyevent": "纪念相机",
    "gun_0003_raid": "水蚀龙铳",
    "gun_0008_raid": "极光来福枪",
    "gun_0014_story_event": "ＳＧ２１",
    "sword_0004": "天羽羽斩",
    "sword_0005": "杜兰德尔",
    "sword_0011": "海姆达尔之剑",
    "sword_0012": "普罗米修斯之剑",
    "sword_0019": "黑龙雷剑",
    "sword_0020_coop": "极彩宝石双剑",
    "sword_0022_boss_unique": "死皇之剑",
    "sword_0025_boss_unique": "海渊棘刃",
    "sword_0026_PCollab": "公主之剑",
    "sword_0028": "提尔锋",
    "sword_0029_boss_unique": "枢机卿",
    "sword_0030_coop": "牛鬼之尾",
    "sword_0031_storyevent": "盟约之剑",
    "sword_0032_score": "天府剑",
    "sword_0033_decay": "斯库尔之剑",
    "sword_0034_raid": "歼风龙剑",
    "sword_0036_storyevent": "希望誓剑",
    "sword_0037_coop": "流水刃剑",
    "sword_0038_storyevent": "基因切割者",
    "sword_0039_Gcollab": "格拉墨",
    "sword_0040_boss_unique": "杀生石匕首",
    "sword_0041_storyevent": "水晶刃",
    "sword_0042_decay": "朱图尔纳之扇",
    "sword_0043_boss_unique": "破坏之雷",
    "sword_0044_storyevent": "紫电真打",
    "sword_0045_score": "七杀鞭",
    "sword_0046_haniwa": "哈尼帕纽斯",
    "sword_0047_scollab": "勇者的扩音器",
    "sword_0050_boss_unique": "鬼柴刀",
    "sword_0051_storyevent": "勿忘罪剑",
    "sword_0054_coop": "烈焰刃剑",
    "sword_0055_story_event": "WBR-01",
    "sword_0056_score": "天梁刀",
    "sword_0057_newbie": "星芥镰剑",
    "sword_0058_PCollab": "兔兔长剑",
    "sword_0059_storyevent": "羊角大剑",
    "sword_0060_raid": "无妨剑",
    "sword_0061": "欢喜赠礼",
    "sword_0062_storyevent": "冲突",
    "sword_0063_storyevent": "胜利大剑",
    "sword_0064_raid": "酸空匕",
    "sword_0065_raid": "噩梦羽",
    "sword_0068_coop": "疾风锐剑",
    "sword_0070_epuration": "解放者",
    "sword_0072_storyevent": "九归一剑",
    "sword_0073_raid": "朱安里克",
    "axe_0008": "乌贡瓦萨拉",
    "axe_0009": "雷神之锤",
    "axe_0010": "死亡镰刀",
    "axe_0017": "虎王斧",
    "axe_0018_boss_unique": "死皇之斧",
    "axe_0020_raid": "凶暗龙镰",
    "axe_0022_storyevent": "前鬼之斧",
    "axe_0023_RCollab": "流星锤",
    "axe_0024": "帕拉修",
    "axe_0025_decay": "百臂巨人之斧",
    "axe_0026_raid": "歼风龙斧",
    "axe_0027_coop": "分海棒",
    "axe_0028_boss_unique": "镇压",
    "axe_0029_storyevent": "虚城斧",
    "axe_0030": "灼钺",
    "axe_0031_haniwa": "哈尼勒斯",
    "axe_0032_raid": "镇痛剂",
    "axe_0035_boss_unique": "豪缝熊Z",
    "axe_0036_haniwa": "哈尼可利",
    "axe_0037": "悲叹死镰",
    "axe_0038_haniwa": "哈尼哈加玛",
    "axe_0039_haniwa": "哈尼古斯塔",
    "axe_0040_raid": "破刃镰",
    "axe_0041": "金刚镰",
    "spear_0005": "马尔特",
    "spear_0011": "俄刻阿诺斯之枪",
    "spear_0016": "灵树之枪",
    "spear_0017": "海王之枪",
    "spear_0018": "兽将之矛",
    "spear_0020_boss_unique": "古王之枪",
    "spear_0021_boss_unique": "暴食之枪",
    "spear_0022_coop": "方天画戟",
    "spear_0023_boss_unique": "父祖战棍",
    "spear_0025": "伏特电击枪",
    "spear_0026_storyevent": "天狗堂之笔",
    "spear_0028_score": "天同枪",
    "spear_0029_raid": "水蚀龙枪",
    "spear_0030_boss_unique": "警备",
    "spear_0033_Gcollab": "布里欧纳克",
    "spear_0034_haniwa": "哈尼克利特",
    "spear_0035_boss_unique": "岩融",
    "spear_0036_raid": "月之舞",
    "spear_0037_newbie": "星芥二叉枪",
    "spear_0038_boss_unique": "怨嗟之枪",
    "spear_0039_boss_unique": "怨嗟逆枪",
    "spear_0040_raid": "怠惰枪",
    "spear_0041_haniwa": "哈尼特肯",
    "bow_0009": "埃俄罗斯之弓",
    "bow_0010": "流星弓",
    "bow_0014": "愚者之弓",
    "bow_0016": "捕食者",
    "bow_0017_raid": "光芒龙弓",
    "bow_0018_coop": "海马雷弓",
    "bow_0019_raid": "灼炎龙弓",
    "bow_0020_score": "天相弓",
    "bow_0022": "米斯特汀",
    "bow_0025_raid": "二度弦",
    "bow_0026_decay": "海伯利安之弓",
    "bow_0028_boss_unique": "风将强弓",
    "bow_0029_decay": "俄耳甫斯竖琴",
    "bow_0030_haniwa": "哈尼卡西",
    "bow_0031_newbie": "星芥复合弓",
    "bow_0033_raid": "至止羽",
    "bow_0035_haniwa": "哈尼戈",
    "book_0009": "占事略决",
    "book_0013": "圣典",
    "book_0014": "妖怪百名账",
    "book_0015_storyevent": "瓦伦特伯爵的笔记",
    "book_0016_boss_unique": "死皇之书",
    "book_0017_boss_unique": "傲慢之书",
    "book_0018_PCollab": "C・魔法书",
    "book_0020_raid": "水蚀龙书",
    "book_0022_raid": "黑龙雷书",
    "book_0024_RCollab": "露格尼卡童话抄本",
    "book_0025_decay": "达佛涅斯石板",
    "book_0026": "太平清领",
    "book_0027_haniwa": "哈尼克西美尼",
    "book_0028_storyevent": "阿尔凯乌斯禁书",
    "book_0029_scollab": "翻旧了的小说",
    "book_0032_story_event": "梦想史记",
    "book_0033_newbie": "星芥异本",
    "book_0034_haniwa": "哈尼拉达姆",
    "book_0036_storyevent": "庆典机密",
    "book_0037_storyevent": "狮王公记",
    "book_0038_storyevent": "艾特兰报告",
    "staff_0009": "星盘杖",
    "staff_0013": "冥王锡杖",
    "staff_0015": "潮汐之杖",
    "staff_0016_raid": "灼炎龙杖",
    "staff_0017_boss_unique": "古王之杖",
    "staff_rare5_24_7": "7月24日",
    "staff_0019_boss_unique": "怠惰之杖",
    "staff_0020_boss_unique": "父祖王锡",
    "staff_0021_storyevent": "莫斯尼亚指挥棒",
    "staff_0024_raid": "糖果长杖",
    "staff_0025": "湛蓝魔杖",
    "staff_0026_raid": "圣柊棘杖",
    "staff_0027_boss_unique": "束缚",
    "staff_0029_boss_unique": "鸣狐之杖",
    "staff_0030_haniwa": "哈尼诺涅",
    "staff_0033_Pcollab": "宇宙蓝色魔杖",
    "staff_0034_boss_unique": "怨嗟之杖",
    "staff_0037_decay": "奥西里斯之杖",
    "staff_0040_raid": "错乱沿",
    "staff_0041_storyevent": "替身虚空",
    "staff_0042_haniwa": "哈尼雷亚思",
    "staff_0044": "酒神权杖",
    "fist_0009": "奥库斯之拳",
    "fist_0017_boss_unique": "古王之拳",
    "fist_0019_boss_unique": "父祖拳套",
    "fist_0020_boss_unique": "海渊钩爪",
    "fist_0021_storyevent": "虚城拳",
    "fist_0023": "图腾拳套",
    "fist_0024_raid": "捣蛋钩爪",
    "fist_0025_storyevent": "碎墙拳",
    "fist_0026_raid": "圣柊笼手",
    "fist_0027": "波利克斯",
    "fist_0028_storyevent": "胜利坚守者",
    "fist_0029_boss_unique": "鲨牙拘拳",
    "fist_0030_haniwa": "哈尼克托耳",
    "fist_0032_boss_unique": "熊岚",
    "fist_0033_raid": "平行论",
    "fist_0035_newbie": "星芥指虎",
    "fist_0036": "位高责重之环",
    "fist_0039_raid": "无情拳",
    "fist_0040_haniwa": "哈尼雷伊",
    "shield_0007": "天磐盾",
    "shield_0011": "护神大盾",
    "shield_0012": "太古之盾",
    "shield_0013": "阻碍者",
    "shield_0014_xmas": "圣铃圆盾",
    "shield_0018_boss_unique": "海渊壳盾",
    "shield_0020_boss_unique": "乡愁",
    "shield_0022_storyevent": "怨念巨盾",
    "shield_0025_boss_unique": "风将骨盾",
    "shield_0026_storyevent": "一兽王盾",
    "shield_0028_haniwa": "哈尼霍普隆",
    "shield_0029_newbie": "星芥狮盾",
    "shield_0031_haniwa": "哈尼霍木拉",
    "shield_thunderdoor": "城门盾",
    "acce_0001_total": "水滴吊坠",
    "acce_0002": "驱动芯片",
    "acce_0003": "双牙项链",
    "acce_0004": "世界树的晨露",
    "acce_0005_PCollab": "爱梅斯护符",
    "acce_0007_total": "水滴手镯",
    "acce_0008_ZCollab": "少女的蝴蝶结",
    "acce_0009_ZCollab": "某人的墨镜",
    "acce_0010_ZCollab": "似乎很重要的绷带",
    "acce_0011_storyevent": "基因组穿孔器",
    "acce_0013_RCollab": "仿制品徽章",
    "acce_0014_boss_unique": "八咫镜",
    "acce_0015_boss_unique": "八尺琼勾玉",
    "acce_0016_total": "水滴项圈",
    "acce_0017_total": "缘环吊坠",
    "acce_0018_decay": "得摩斯手镯",
    "acce_0019_total": "交融手镯",
    "acce_0020_boss_unique": "蝎尾坠",
    "acce_0021_storyevent": "清夏缎带",
    "acce_0022_scollab": "候补团员袖章",
    "acce_0023_boss_unique": "风将弹袋",
    "acce_0024_raid_revival": "光芒龙冠",
    "acce_0025_haniwa": "哈尼翁",
    "acce_0026_storyevent": "黑色皮包",
    "acce_0027_newbie": "星芥手镯",
    "acce_0028_newbie": "星芥腰带",
    "acce_0029_newbie": "星芥宝冠",
    "acce_0030_storyevent": "止战徽记",
    "acce_0031_Pcollab": "捣蛋礼物",
    "acce_0032_boss_unique": "怨嗟外套",
    "acce_0034_storyevent": "方框眼镜",
    "acce_0035_total": "交融耳环",
    "acce_0038_storyevent": "原始生毛药剂NR",
    "acce_0042_storyevent": "条纹泳圈",
    "acce_0044_haniwa": "哈尼巴尔",
    "acce_0045_total": "交融胸针",
    "gun_rare5_positron_shooter": "正电子发射器",
    "gun_0002": "船上式343号铳",
    "gun_0004_boss_unique": "疯狂者",
    "gun_0005_storyevent": "ＭＭ２８",
    "gun_0006_raid": "凶暗龙铳",
    "gun_0009_coop": "华弩魔-II",
    "gun_0010_storyevent": "飞鹫爆裂炮",
    "gun_0011_score": "天机铳",
    "gun_0012_boss_unique": "ＳＫ５０９",
    "gun_0013_boss_unique": "叉鬼猎铳",
    "gun_0015_haniwa": "哈尼兰切",
    "gun_0016_newbie": "星芥骑兵铳",
    "gun_0017_storyevent": "走私步枪",
    "gun_0018_haniwa": "哈尼海耶",
}
# 如果name和filename不同，则添加到下面
filenames = {
    "領主の少年?ローラン": "少年领主",
    "stella_copy_known": "面具术士",
    "stella_copy_mask_off": "史黛拉？",
    "devil_commander_known": "魔族男性",
    "devil_commander_unknown": "？？？",
    "gaunt_women": "消瘦的女子",
    "old_mermaid_man_known": "爷爷",
    "refugees_boy_known": "难民男孩",
    "refugees_women": "难民女子",
    "refugees_child": "难民小孩",
    "refugees_man": "难民男子",
    "knight_leaders": "干部青年",
    "knight_length_mob": "骑士长",
    "knight_mob": "骑士",
    "soldier_mob": "士兵",
    "guard_man": "警卫兵",
    "elf_princess_disguise_unknown": "？？？",
    "elf_princess_disguise_known": "精灵少女",
    "elf_princess_disguise": "莉艾尔",
    "tree_people": "木桩",
    "elf_warrior_unknown": "？？？",
    "elf_warrior": "精灵战士",
    "elf_princess_known": "莉艾尔？",
    "elves_voice_only": "精灵们的声音",
    "refugees_mob": "难民",
    "crude_man": "粗鲁的人",
    "gloomy_man": "阴郁的人",
    "devil_sismama_unknown": "？？？",
    "demons_people": "魔族",
    "demons_soldier": "魔族之兵",
    "victory_voice": "战斗声",
    "demons_executive": "魔族干部",
    "flame_witch_known": "夏可缇",
    "devil_commander_known": "伊尔比斯",
    "gaunt_women": "",
    "old_mermaid_man_known": "",
    "refugees_boy_known": "艾力克",
    "refugees_women": "",
    "refugees_child": "",
    "refugees_man": "",
    "knight_leaders": "",
    "knight_length_mob": "",
    "knight_mob": "",
    "soldier_mob": "",
    "guard_man": "",
    "elf_princess_disguise_unknown": "",
    "elf_princess_disguise_known": "", # 莉艾尔
    "elf_princess_disguise": "",
    "tree_people": "",
    "devil_leader_known": "",
    "devil_leader_known2": "艾迪凯斯",
    "elf_warrior_unknown": "",
    "elf_warrior": "",
    "elf_princess_known": "艾丝缇莉艾尔",
    "elves_voice_only": "",
    "refugees_mob": "",
    "crude_man": "",
    "gloomy_man": "",
    "devil_sismama_unknown": "梅莉",
    "devil_ylbis": "伊尔比斯_ylbis",
    "demons_people": "",
    "demons_soldier": "",
    "victory_voice": "",
    "demons_executive": "",
}
# 技能名
skillnames = {
    "atk_all_direction": "朝不同方向攻击",
    "atk_surround": "攻击自己周围区域",
    # "atk_back": "",
    "atk_common": "攻击",
    "atk_field": "领域全体效果",
    "atk_four_ranges": "上下左右方向攻击",
    "atk_four_ranges_cross": "对角线方向攻击",
    "atk_front": "前进攻击",
    "atk_front_back": "前后方向攻击",
    "atk_go_direction": "行进方向攻击",
    "atk_hit": "对击中的敌人有效",
    "atk_nearest": "攻击最近的敌人",
    "fever": "FEVER槽提升",
    "flip": "强化弹射伤害上升",
    "float": "浮游",
    "heal": "治疗",
    "invincible": "无敌",
    "multi_ball": "协力球",
    "multi_bomb": "炸弹协力球",
    "penet": "贯穿",
    "poison": "中毒",
    "regene": "再生",
    "resist": "弱体抗性上升",
    "resist_up_purple": "暗属性抗性上升",
    "resist_up_red": "火属性抗性上升",
    "resist_up_white": "光属性抗性上升",
    "skill_str_up": "技能伤害上升",
    "str_up": "攻击力上升",
}
# 属性
attrs = {
    "0": "火",
    "1": "水",
    "2": "雷",
    "3": "风",
    "4": "光",
    "5": "暗",
    "6": "无",
}
# 种族
races = {
    "Human": "人",
    "Element": "精灵",
    "Devil": "魔",
    "Beast": "兽",
    "Machine": "机械",
    "Mystery": "妖",
    "Dragon": "龙",
    "Undead": "不死",
    "Aquatic": "水栖",
    "Plants": "植物",
}
# 性别
genders = {
    "Male": "男",
    "Female": "女",
    "Ririi": "莉莉",
    "Unknown": "不明",
}
# 类型
_types = {
    "1": "格斗",
    "0": "剑士",
    "2": "射击",
    "3": "辅助",
    "4": "特殊",
}
# 职责
stances = {
    "Attacker": "进攻",
    "Tank": "防护",
    "Healer": "治疗",
    "Supporter": "支援",
    "Jammer": "妨碍",
    "Balance": "平衡",
}
tags = {
"5200 シングル上級": "sec-5200li 高级", 
"5200 シングル超級": "超级sec-5200li 单超机", 
"5200 マルチ上級": "sec-5200li 高级", 
"5200 マルチ上級+": "sec-5200li 高+", 
"5200 マルチ中級": "sec-5200li 中级", 
"5200 マルチ超級": "超级sec-5200li 多超机", 
"7章ボス メイン": "7章boss主线", 
"8章ボス メイン": "8章boss主线", 
"AI CSB超級+": "ai csb超级+", 
"AI シングル超級": "ai 单超级", 
"AI マルチ上級": "ai 高级", 
"AI マルチ超級": "ai 多超级", 
"AI(CD) CSB地獄": "ai cd 地狱", 
"AI(追憶) CSB地獄": "ai 追忆 地狱", 
"SecMk2 シングル超級": "secmk2 单超级", 
"SecMk2 マルチ上級+": "secmk2 高+", 
"TA21/02 Lv1": "试炼 竞速21/02 Lv1", 
"TA21/02 Lv4": "试炼 竞速21/02 Lv4", 
"TA雷試練  ": "奔雷的试炼 竞速", 
"TA風試練  ": "旋风的试炼 竞速", 
"⛄G マルチ超級": "圣夜的淘气鬼 多超级", 
"ゆらぎ光 Lv50": "摇曳的迷宫光 Lv50", 
"ゆらぎ光 Lv60": "摇曳的迷宫光 Lv60", 
"ゆらぎ光 シングル上級": "摇曳的迷宫光 高级", 
"ゆらぎ水 Lv50": "摇曳的迷宫水 Lv50", 
"ゆらぎ水 Lv60": "摇曳的迷宫水 Lv60", 
"ゆらぎ水 シングル上級": "摇曳的迷宫水 高级", 
"ゆらぎ火 Lv50": "摇曳的迷宫火 Lv50", 
"ゆらぎ火 Lv60": "摇曳的迷宫火 Lv60", 
"ゆらぎ火 シングル上級": "摇曳的迷宫火 高级", 
"ゆらぎ闇 Lv50": "摇曳的迷宫暗 Lv50", 
"ゆらぎ闇 Lv60": "摇曳的迷宫暗 Lv60", 
"ゆらぎ闇 シングル上級": "摇曳的迷宫暗 高级", 
"ゆらぎ雷 Lv50": "摇曳的迷宫雷 Lv50", 
"ゆらぎ雷 Lv60": "摇曳的迷宫雷 Lv60", 
"ゆらぎ雷 シングル上級": "摇曳的迷宫雷 高级", 
"ゆらぎ風 Lv50": "摇曳的迷宫风 Lv50", 
"ゆらぎ風 Lv60": "摇曳的迷宫风 Lv60", 
"ゆらぎ風 シングル上級": "摇曳的迷宫风 高级", 
"アドミ CSB地獄": "管理者 地狱光", 
"アドミ CSB超級+": "管理者 超级+", 
"アドミ シングル上級": "管理者 高级", 
"アドミ シングル上級+": "管理者 高+", 
"アドミ シングル超級": "管理者 单超光", 
"アドミ マルチ上級": "管理者 高级", 
"アドミ マルチ上級+": "管理者 高+", 
"アドミ マルチ中級": "管理者 中级", 
"アドミ マルチ超級": "管理者 多超光", 
"アビ獣 極": "深渊之兽 阿比斯 abs 极", 
"アビ獣 無印": "深渊之兽 阿比斯 abs 無", 
"アビ獣 真": "深渊之兽 阿比斯 abs 真", 
"イルフリ CSB超級+": "2.5周年 废龙伊尔弗里德 csb超级+", 
"イルフリ マルチ上級": "2.5周年 废龙伊尔弗里德 高级", 
"イルフリ マルチ超級": "2.5周年 废龙伊尔弗里德 多超级", 
"エギ CSB地獄": "诅咒弧魔艾基尔 地狱暗", 
"エギ CSB超級+": "诅咒弧魔艾基尔 超级+", 
"エギ シングル超級": "诅咒弧魔艾基尔 单超暗", 
"エギ マルチ上級": "诅咒弧魔艾基尔 高级", 
"エギ マルチ上級+": "诅咒弧魔艾基尔 高+", 
"エギ マルチ中級": "诅咒弧魔艾基尔 中级", 
"エギ マルチ超級": "诅咒弧魔艾基尔 多超暗", 
"エンヴィー シングル超級": "暗怨 单超怨", 
"エンヴィー マルチ上級": "暗怨 高级", 
"エンヴィー マルチ上級+": "暗怨 高+", 
"エンヴィー マルチ超級": "暗怨 多超怨", 
"オブリビ CSB超級+": "虚假的人偶公主 迷失遗忘者 超级+", 
"オブリビ シングル超級": "虚假的人偶公主 迷失遗忘者 单超级", 
"オブリビ マルチ上級": "虚假的人偶公主 迷失遗忘者 高级", 
"オブリビ マルチ超級": "虚假的人偶公主 迷失遗忘者 多超级", 
"オブリビ(追憶) CSB地獄": "虚假的人偶公主 迷失遗忘者 追忆 地狱", 
"ガーディアン マルチ超級": "公主连结联动 方舟守护者 多超级", 
"キノ500  ": "キノ500", 
"キノ600  ": "キノ600", 
"グラトド シングル中級": "凉宫联动 古拉托顿 中级", 
"グラトド マルチ上級": "凉宫联动 古拉托顿 高级", 
"グラトド マルチ上級+": "凉宫联动 古拉托顿 高+", 
"グラトド マルチ中級": "凉宫联动 古拉托顿 中级", 
"グラトド マルチ超級": "凉宫联动 古拉托顿 多超级", 
"グラトド(CD) シングル超級": "凉宫联动 古拉托顿 cd 单超级", 
"コンダク シングル超級": "指挥者 单超级", 
"ゴレ CSB地獄": "废墟魔像 地狱火", 
"ゴレ CSB超級+": "废墟魔像 超级+", 
"ゴレ シングル上級+": "废墟魔像 高+", 
"ゴレ シングル超級": "废墟魔像 单超火", 
"ゴレ マルチ上級": "废墟魔像 高级", 
"ゴレ マルチ上級+": "废墟魔像 高+", 
"ゴレ マルチ中級": "废墟魔像 中级", 
"ゴレ マルチ超級": "废墟魔像 多超火", 
"ジンドラ シングル超級": "大海的遗产 基因巨龙 单超级", 
"ジンドラ マルチ上級": "大海的遗产 基因巨龙 高级", 
"ジンドラ マルチ上級+": "大海的遗产 基因巨龙 高+", 
"スキル演武  ": "无限演武", 
"ステバス CSB超級+": "共誓黎明 星辰破坏者 超级+", 
"ステバス マルチ上級": "共誓黎明 星辰破坏者 高级", 
"ステバス マルチ超級": "共誓黎明 星辰破坏者 多超级", 
"ステバス(CD) CSB地獄": "共誓黎明 星辰破坏者 cd 地狱", 
"ステバス(追憶) CSB地獄": "共誓黎明 星辰破坏者 追忆 地狱", 
"ダーリン シングル上級+": "热情的爱河★漂流者 虚假达令Ⅱ 高+", 
"ダーリン シングル超級": "热情的爱河★漂流者 虚假达令Ⅱ 单超级", 
"ダーリン マルチ上級+": "热情的爱河★漂流者 虚假达令Ⅱ 高+", 
"チョコ鳥(CD) シングル超級": "情人节凤凰 cd 单超级", 
"チョコ鳥(追憶) CSB地獄": "情人节凤凰 追忆 地狱", 
"デオフラ CSB超級+": "噬星兽 csb超级+", 
"デオフラ マルチ超級": "噬星兽 多超级", 
"デオフラ(CD) シングル超級": "噬星兽 cd 单超级", 
"デオフラ(追憶) CSB地獄": "噬星兽 追忆 地狱", 
"ドール マルチ上級": "虚假的人偶公主 步兵人偶 高级", 
"ドール マルチ上級+": "虚假的人偶公主 步兵人偶 高+", 
"ハリダル シングル超級": "共誓黎明 哈里达尔 单超级", 
"ハリダル マルチ上級": "共誓黎明 哈里达尔 高级", 
"ハリダル マルチ上級+": "共誓黎明 哈里达尔 高+", 
"パラアビ CSB超級+": "パラアビ csb超级+", 
"パラアビ マルチ超級": "パラアビ 多超级", 
"プル👑 シングル超級": "プル👑 单超级", 
"プル👑 マルチ超級": "プル👑 多超级", 
"プロキオ CSB超級+": "变异体 超级+", 
"プロキオ マルチ超級": "变异体 多超级", 
"プロキオ(追憶) CSB地獄": "变异体 追忆 地狱", 
"マグノス CSB超級+": "王键马格努斯 火狮子 超级+", 
"マグノス マルチ超級": "王键马格努斯 火狮子 多超级", 
"マグノス(追憶) CSB地獄": "王键马格努斯 火狮子 追忆 地狱", 
"マナ Lv60": "mana Lv60", 
"ヤド CSB地獄": "寄居蟹船长 地狱水", 
"ヤド CSB超級+": "寄居蟹船长 超级+", 
"ヤド シングル超級": "寄居蟹船长 单超水", 
"ヤド マルチ上級": "寄居蟹船长 高级", 
"ヤド マルチ上級+": "寄居蟹船长 高+", 
"ヤド マルチ中級": "寄居蟹船长 中级", 
"ヤド マルチ超級": "寄居蟹船长 多超水", 
"ラヴ CSB超級+": "拉芙 超级+", 
"ラヴ(追憶) CSB地獄": "拉芙 追忆 地狱", 
"ルイガ マルチ上級": "废墟守卫·火 高级", 
"ルイガ マルチ超級": "废墟守卫·火 多超级", 
"レシ CSB地獄": "瑞西塔尔 地狱风", 
"レシ CSB超級+": "瑞西塔尔 超级+", 
"レシ シングル上級+": "瑞西塔尔 高+", 
"レシ シングル超級": "瑞西塔尔 单超风", 
"レシ マルチ上級": "瑞西塔尔 高级", 
"レシ マルチ上級+": "瑞西塔尔 高+", 
"レシ マルチ中級": "瑞西塔尔 中级", 
"レシ マルチ超級": "瑞西塔尔 多超风", 
"ロメロ マルチ上級+": "佐贺联动复刻 罗梅罗 高+", 
"ロメロ マルチ超級": "佐贺联动复刻 罗梅罗 多超级", 
"闇必殺ハニワ シングル超級": "暗土俑 技伤 单超级", 
"闇廃竜 シングル上級+": "暗荒龙 高+", 
"闇廃竜 マルチ超級": "暗荒龙 多超级", 
"闇廃竜 マルチ上級+": "暗荒龙 高+", 
"闇鳳 マルチ超級": "暗凤 多超凤", 
"闇鳳 マルチ上級": "暗凤 高级", 
"闇鳳 マルチ上級+": "暗凤 高+", 
"闇強振ハニワ シングル超級": "暗土俑 pf 单超级", 
"闇直撃ハニワ シングル超級": "暗土俑 直击 单超级", 
"闇ハニワ シングル超級": "暗土俑 单超级", 
"宝物闇  ": "宝物域暗", 
"宝物風  ": "宝物域风", 
"宝物光  ": "宝物域光", 
"宝物火  ": "宝物域火", 
"宝物雷  ": "宝物域雷", 
"宝物水  ": "宝物域水", 
"崩壊闇 Lv50": "崩坏域暗 Lv50", 
"崩壊闇 Lv60": "崩坏域暗 Lv60", 
"崩壊闇 Lv70": "崩坏域暗 Lv70", 
"崩壊風 Lv70": "崩坏域风 Lv70", 
"崩壊光 Lv70": "崩坏域光 Lv70", 
"崩壊火 Lv70": "崩坏域火 Lv70", 
"崩壊雷 Lv70": "崩坏域雷 Lv70", 
"崩壊水 Lv50": "崩坏域水 Lv50", 
"崩壊水 Lv60": "崩坏域水 Lv60", 
"崩壊水 Lv70": "崩坏域水 Lv70", 
"歩兵粛清 マルチ超級": "步兵肃清者 多人超级", 
"超人 CSB超級+": "大海的遗产 超人泽古拉 超级+", 
"超人 マルチ超級": "大海的遗产 超人泽古拉 多超级", 
"超人(追憶) CSB地獄": "大海的遗产 超人泽古拉 追忆 地狱", 
"翠機兵 マルチ超級": "绿机兵 多超级", 
"翠機兵 マルチ決戦級": "绿机兵 多人决战", 
"大蛇 シングル超級": "大蛇 单超蛇", 
"大蛇 マルチ超級": "大蛇 多超蛇", 
"大蛇 マルチ上級": "大蛇 高级", 
"大蛇 マルチ上級+": "大蛇 高+", 
"二羽鳥 マルチ超級": "异界漂泊潭 比翼的使魔 多超级", 
"二羽鳥 マルチ上級+": "异界漂泊潭 比翼的使魔 高+", 
"乏竜の宴 シングル超級": "战阵之宴 单超级", 
"風廃竜 シングル超級": "风荒龙 单超级", 
"風廃竜 シングル上級+": "风荒龙 高+", 
"風廃竜 シングル中級": "风荒龙 中级", 
"風廃竜 マルチ超級": "风荒龙 多超级", 
"風廃竜 マルチ上級": "风荒龙 高级", 
"風廃竜 マルチ上級+": "风荒龙 高+", 
"風雷神 シングル上級+": "风雷神 高+", 
"風雷神 マルチ超級": "风雷神 多超级", 
"風雷神 マルチ上級+": "风雷神 高+", 
"風直撃ハニワ シングル超級": "风土俑 直击 单超级", 
"風ハニワ シングル超級": "风土俑 单超级", 
"風レーヌ マルチ超級": "碧之女王 多超级", 
"紅機兵 マルチ超級": "红机兵 多超级", 
"紅機兵 マルチ決戦級": "红机兵 多人決戦级", 
"紅機兵 マルチ上級": "红机兵 高级", 
"紅機兵 マルチ上級+": "红机兵 高+", 
"光必殺ハニワ シングル超級": "光土俑 技伤 单超级", 
"光廃竜 シングル超級": "光荒龙 单超级", 
"光廃竜 マルチ超級": "光荒龙 多超级", 
"光廃竜 マルチ上級+": "光荒龙 高+", 
"光廃竜(CD) シングル超級": "光荒龙 cd 单超级", 
"光廃竜(CD) シングル上級": "光荒龙 cd 高级", 
"光廃竜(CD) シングル中級": "光荒龙 cd 中级", 
"光強振ハニワ シングル超級": "光土俑 pf 单超级", 
"光直撃ハニワ シングル超級": "光土俑 直击 单超级", 
"光蜘蛛 マルチ超級": "光蜘蛛 多超级", 
"光蜘蛛 マルチ地獄級": "光蜘蛛 多人地狱级", 
"光ハニワ シングル超級": "光土俑 单超级", 
"黒ドラ シングル超級": "黒ドラ 单超级", 
"黒ドラ マルチ上級+": "黒ドラ 高+", 
"黒ドラ(ブラクロ) マルチ超級": "黒ドラ(ブラクロ) 多超级", 
"虎 CSB超級+": "白虎 超级+", 
"虎 CSB地獄": "白虎 地狱雷", 
"狐 シングル超級": "妖狐 单超狐", 
"虎 シングル超級": "白虎 单超雷", 
"狐 シングル上級": "妖狐 高级", 
"狐 マルチ超級": "妖狐 多超狐", 
"虎 マルチ超級": "白虎 多超雷", 
"狐 マルチ上級": "妖狐 高级", 
"虎 マルチ上級": "白虎 高级", 
"狐 マルチ上級+": "妖狐 高+", 
"虎 マルチ上級+": "白虎 高+", 
"虎 マルチ中級": "白虎 中级", 
"画竜 シングル超級": "画龙 单超级", 
"画竜 マルチ上級+": "画龙 高+", 
"火廃竜 シングル超級": "火荒龙 单超级", 
"火廃竜 マルチ超級": "火荒龙 多超级", 
"火廃竜 マルチ上級": "火荒龙 高级", 
"火廃竜 マルチ上級+": "火荒龙 高+", 
"火魔 マルチ超級": "火魔 多超级", 
"火魔 マルチ上級+": "火魔 高+", 
"火ハニワ シングル超級": "火土俑 单超级", 
"火レーヌ マルチ超級": "赤之女王 多超级", 
"火レーヌ マルチ上級+": "赤之女王 高+", 
"鮫兄弟 シングル超級": "背鳍三兄弟 鲨鱼 单超鲨", 
"鮫兄弟 シングル上級": "背鳍三兄弟 鲨鱼 高级", 
"鮫兄弟 シングル上級+": "背鳍三兄弟 鲨鱼 高+", 
"鮫兄弟 シングル中級": "背鳍三兄弟 鲨鱼 中级", 
"鮫兄弟 マルチ超級": "背鳍三兄弟 鲨鱼 多超鲨", 
"鮫兄弟 マルチ上級": "背鳍三兄弟 鲨鱼 高级", 
"鮫兄弟 マルチ上級+": "背鳍三兄弟 鲨鱼 高+", 
"鮫兄弟 マルチ中級": "背鳍三兄弟 鲨鱼 中级", 
"雷必殺ハニワ シングル超級": "雷土俑 技伤 单超级", 
"雷必殺ハニワ シングル上級": "雷土俑 技伤 高级", 
"雷廃竜 マルチ超級": "雷荒龙 多超级", 
"雷廃竜 マルチ上級+": "雷荒龙 高+", 
"雷亀 シングル中級": "雷龟 中级", 
"雷亀 マルチ超級": "雷龟 多超龟", 
"雷強振ハニワ シングル超級": "雷土俑 pf 单超级", 
"雷強振ハニワ シングル上級": "雷土俑 pf 高级", 
"雷直撃ハニワ シングル超級": "雷土俑 直击 单超级", 
"雷ハニワ シングル超級": "雷土俑 单超级", 
"龍喰い CSB超級+": "噬龙者 csb超级+", 
"龍喰い マルチ超級": "噬龙者 多超级", 
"龍喰い マルチ上級": "噬龙者 高级", 
"龍喰い(追憶) CSB地獄": "噬龙者 追忆 csb地狱", 
"木 シングル上級": "雷霆树妖 高级", 
"木 シングル中級": "雷霆树妖 中级", 
"木 マルチ超級": "雷霆树妖 多超树", 
"木 マルチ上級": "雷霆树妖 高级", 
"木 マルチ上級+": "雷霆树妖 高+", 
"女帝粛清 CSB地獄": "女帝肃清者 csb地狱", 
"前後鬼 CSB超級+": "前后鬼 csb超级+", 
"前後鬼 マルチ超級": "前后鬼 多超级", 
"前後鬼 マルチ上級": "前后鬼 高级", 
"前後鬼(追憶) CSB地獄": "前后鬼 追忆 地狱", 
"前後鬼(CD) シングル上級": "前后鬼 cd 高级", 
"瑞狐(CD) シングル超級": "瑞妖狐 cd 单超级", 
"僧正粛清 マルチ超級": "僧正肃清 多超级", 
"時闇試練  ": "极时暗试炼", 
"時風試練  ": "极时风试炼", 
"時光試練  ": "极时光试炼", 
"時火試練  ": "极时火试炼", 
"時雷試練  ": "极时雷试炼", 
"時水試練  ": "极时水试炼", 
"水必殺ハニワ シングル超級": "水土俑 技伤 单超级", 
"水廃竜 シングル超級": "水荒龙 单超级", 
"水廃竜 マルチ超級": "水荒龙 多超级", 
"水廃竜 マルチ上級+": "水荒龙 高+", 
"水鬼 シングル超級": "水鬼 单超级", 
"水鬼 マルチ超級": "水鬼 多超级", 
"水鬼(CD) シングル超級": "水鬼 cd 单超级", 
"水強振ハニワ シングル超級": "水土俑 pf 单超级", 
"水狂乱ハニワ シングル超級": "水土俑 狂乱 单超级", 
"水ハニワ シングル超級": "水土俑 单超级", 
"水レーヌ マルチ超級": "青之女王 多超级", 
"水レーヌ マルチ上級+": "青之女王 高+", 
"烏賊 シングル超級": "潮汐巨妖 单超乌贼", 
"烏賊 マルチ上級": "潮汐巨妖 高级", 
"烏賊(CD) シングル超級": "潮汐巨妖 cd 单超乌贼", 
"梟 シングル初級": "梟 初级", 
"梟 マルチ初級": "梟 初级", 
"熊 シングル超級": "火熊 单超熊", 
"熊 マルチ超級": "火熊 多超熊", 
"熊 マルチ上級": "火熊 高级", 
"熊 マルチ上級+": "火熊 高+", 
"異形粛清 マルチ超級": "異形肃清者 多超级", 
"刈り取り マルチ超級": "刈り取り 多超级", 
"刈り取り マルチ上級+": "刈り取り 高+", 
"硬人形 闇": "硬人形 暗", 
"硬人形 風": "硬人形 风", 
"硬人形 光": "硬人形 光", 
"硬人形 火": "硬人形 火", 
"硬人形 雷": "硬人形 雷", 
"硬人形 水": "硬人形 水", 
"幽玄闇 28階層～": "幽玄暗", 
"幽玄風 28階層～": "幽玄风", 
"幽玄光 28階層～": "幽玄光", 
"幽玄雷 28階層～": "幽玄雷", 
"幽玄水 28階層～": "幽玄水", 
"直攻演武  ": "直攻演武", 
"猪 シングル超級": "风猪 单超猪", 
"猪 シングル上級": "风猪 高级", 
"猪 マルチ超級": "风猪 多超猪", 
"猪 マルチ上級": "风猪 高级", 
"猪 マルチ上級+": "风猪 高+", 
"🎃 マルチ超級": "🎃 多超级", 
"🎃(CD) シングル超級": "🎃 cd 单超级", 
"🐍 マルチ上級+": "🐍 高+", 
"🐍 マルチ超級": "🐍 多超级", 
"🐑 CSB超級+": "🐑 csb超级+", 
"🐑 マルチ超級": "🐑 多超级", 
"🚁 CSB超級+": "直升机 csb超级+", 
"🚁 マルチ上級": "直升机 高级", 
"🚁 マルチ超級": "直升机 多超级", 
"１０秒台": "10秒台", 
"オート可能": "auto可能", 
"オート向け": "auto向", 
"コンボ": "combo", 
"fever": "fever", 
"フィーバー": "fever", 
"フィーバーコンボ": "fever combo", 
"パワフリダメージ": "pf伤害", 
"パワフリダメージ趣味パーティ": "pf伤害整活", 
"☆4~5不使用": "☆4~5不使用", 
"☆5不使用": "☆5不使用", 
"闇属性": "暗", 
"闇マルボ": "暗面包", 
"セミオート": "半auto", 
"セミオート向け": "半auto向", 
"背水": "背水", 
"編成初心者": "编成新手", 
"即死王レシタール": "不死王瑞西塔尔", 
"操里ユカリコ": "操里缘子", 
"毒": "毒", 
"マルチボール": "多面包", 
"アビ獣": "深渊之兽 abs", 
"風属性": "风", 
"風統一": "风", 
"浮遊": "浮游", 
"高級": "高级", 
"格闘パワフリ": "格斗pf", 
"貫通": "贯穿", 
"棺桶": "棺柩", 
"貫通剣パワフリテンプレが倒せない": "贯通剑pf永续", 
"光属性": "光", 
"高速周回": "回转", 
"渾身": "浑身", 
"火属性": "火", 
"スキルダメージ": "技伤", 
"極時": "极时", 
"あり": "荐", 
"剣士パワフリ": "剑士pf", 
"手動のみ": "仅手操", 
"恒常キャラのみ": "仅限常驻角色", 
"恒常武器(ガチャ除く)のみ": "仅限常驻武器", 
"恒常武器(ガチャ含む)のみ": "仅限常驻武器(含装备池)", 
"耐久": "抗性", 
"多属性": "跨属", 
"雷属性": "雷", 
"連撃": "连击", 
"初心者向け": "萌新专享", 
"マルボフィーバー": "面包fever", 
"マルボダメージ": "面包人伤害", 
"アビリティダメージ": "能力伤害", 
"限定キャラなし": "全常驻角色", 
"射撃パワフリ": "射击pf", 
"崩壊域周回": "深层", 
"manual": "手操", 
"手動": "手操", 
"手動向け": "手操向", 
"water": "水", 
"水属性": "水", 
"速攻": "速刷", 
"EXブースト推奨": "推荐ex", 
"卍速度卍": "卍速度卍", 
"超級武器なし": "无超武", 
"無敵": "无敌", 
"無限": "无限", 
"スキル演武": "无限演武", 
"限定あり": "限定", 
"limited": "限定", 
"限定武器": "限定武器", 
"限定武器あり": "限定武器", 
"EXブースト必須": "需要ex", 
"限定キャラあり": "有限定角色", 
"浴衣": "浴衣", 
"趣味パ": "整活", 
"趣味パーティ": "整活", 
"直撃": "直击", 
"直撃ダメージ": "直击伤害", 
"追憶": "追忆", 
"#精一杯の感謝を": "非常感谢（推特tag活动盘）", 
"のら！": "nora！（火鼠）", 
"へんたいふしんしゃさん": "变态的流氓桑（镜华？）", 
"まっがーれ↓": "扭曲~吧↓", 
"めぐみん": "惠惠", 
"アタッカー編成": "打手盘", 
"アルム": "阿鲁姆", 
"ケモパ": "福瑞盘", 
"サポート編成": "工具盘", 
"スコ剣": "大葱剑", 
"ストーリー": "剧情关卡", 
"ネタパ": "梗盘", 
"パラシュなし": "无羁绊斧", 
"プラチナム": "白金（火02？）", 
"プリイグナイター": "机械芯片", 
"プルパ": "史莱姆盘", 
"マナ稼ぎ": "刷mana盘", 
"ラナーファンクラブ": "水兵同好会", 
"ワンパン": "踢罐", 
"初撃のことしか考えない": "光想着打一拳了", 
"低レアパ": "低星盘", 
"鈍足特攻あり恒常キャラのみ": "迟缓特攻常驻角色盘", 
"固定メンバー向け": "需固定车友", 
"機械パ": "机械队", 
"精霊パ": "精灵队", 
"開幕9チェイン対応": "开幕9chain", 
"魔族パ": "魔族盘", 
"配布限定のみ": "只用送的角色", 
"盆踊り": "盂兰盆舞盘", 
"生首": "Vtuber的脑壳", 
"世界樹の朝露": "世界树的晨露", 
"獣パ": "福瑞盘", 
"添削希望": "希望改一下", 
"条件付き": "有条件", 
"揺らぎ周回": "素材收菜", 
"直攻に救いを": "拯救直击计划"
}
def en2cn(en):
    en = en.replace(".png", "").replace(".jpg", "")
    return names.get(en, "")

def en2f(en):
    en = en.replace(".png", "").replace(".jpg", "")
    return filenames.get(en, names.get(en, ""))

def en2skill(en):
    en = en.split("/")[-1]
    return skillnames.get(en, en)

def en2attr(en):
    return attrs.get(en, en)

def en2race(en):
    en = en.split(",")
    return ",".join([races.get(_, _) for _ in en])

def en2gender(en):
    return genders.get(en, en)

def en2type(en):
    return _types.get(en, en)

def en2stance(en):
    return stances.get(en, en)

def jp2tag(en):
    return tags.get(en, en)

def story_no_chapter():
    wf = open("en2cn.txt", "w+", encoding="utf-8")
    with open("en.txt", "r", encoding="utf-8") as rf:
        line = rf.readline()
        while line:
            line = line.replace("\n", "").replace("\\n", "<br>").split("\t")
            cn = en2cn(line[0])
            f = en2f(line[1])
            if cn == "":
                wf.write("{{对话||" + line[0] + "|" + line[1] + "}}\n")
            else:
                wf.write("{{对话|" + f + "|" + cn + "|" + line[1] + "}}\n")
            line = rf.readline()
    wf.close()

def story_with_chapter():
    chapter = open("enChapter.txt", "r", encoding="utf-8")
    wf = open("en2cn.txt", "w+", encoding="utf-8")
    idx = "00"
    with open("en.txt", "r", encoding="utf-8") as rf:
        line = rf.readline()
        while line:
            line = line.replace("\n", "").replace("\\n", "<br>").split("\t")
            if line[1] == "1":
                line = rf.readline()
                continue
            if idx != line[0]: # new chapter
                idx = line[0]
                c = chapter.readline()
                c = c.replace("\n", "").replace("\\n", "<br>").split("\t")
                wf.write("==" + c[0] + "==\n")
                wf.write("{{折叠|宽度=100%\n")
                wf.write("|标题=剧情梗概\n")
                wf.write("|内容=" + c[1] + "\n")
                wf.write("}}\n")
            cn = en2cn(line[1])
            f = en2f(line[1])
            if cn == "":
                wf.write("{{对话||" + line[1] + "|" + line[2] + "}}\n")
            else:
                wf.write("{{对话|" + f + "|" + cn + "|" + line[2] + "}}\n")
            line = rf.readline()
    wf.close()

if __name__ == "__main__":
    # story
    story_with_chapter()